/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GeraRelatorio.java
 *
 * Created on 17/05/2013, 22:57:28
 */
package sys.taxi.com.br.util;

import java.sql.Connection;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author VGCT
 */
public class GeraRelatorio extends javax.swing.JFrame {

    /** Creates new form GeraRelatorio */
    public GeraRelatorio() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BOTVisualiza = new javax.swing.JButton();
        BOTGeraPdf = new javax.swing.JButton();
        BOTGeraHtml = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BOTVisualiza.setText("Visualiza");
        BOTVisualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTVisualizaActionPerformed(evt);
            }
        });

        BOTGeraPdf.setText("Gera PDF");
        BOTGeraPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTGeraPdfActionPerformed(evt);
            }
        });

        BOTGeraHtml.setText("Gera HTML");
        BOTGeraHtml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTGeraHtmlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(BOTVisualiza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BOTGeraPdf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BOTGeraHtml)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BOTVisualiza)
                    .addComponent(BOTGeraPdf)
                    .addComponent(BOTGeraHtml))
                .addContainerGap(169, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void BOTVisualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTVisualizaActionPerformed
    abreRelatorioT2();
    //abreRelatorioNet();
}//GEN-LAST:event_BOTVisualizaActionPerformed

private void BOTGeraPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTGeraPdfActionPerformed
try{
    Connection con = new ConexaoSQL().getConnection();
    HashMap parametros = new HashMap();
    JasperPrint jp = JasperFillManager.fillReport("C:/Java/ProjetoTCC/src/sys/taxi/com/all/impresao/RPTFuncionarios.jasper", parametros, con);
    JasperExportManager.exportReportToPdfFile(jp, "C:/Java/ProjetoTCC/src/sys/taxi/com/all/impresao");
}catch(Exception e){
    e.printStackTrace();
}
}//GEN-LAST:event_BOTGeraPdfActionPerformed

private void BOTGeraHtmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTGeraHtmlActionPerformed
try{
    Connection con = new ConexaoSQL().getConnection();
    HashMap parametros = new HashMap();
    JasperPrint jp = JasperFillManager.fillReport("caminho arquivo .jasper", parametros, con);
    JasperExportManager.exportReportToHtmlFile(jp, "Caminho a ser salvo");
}catch(Exception e){
    e.printStackTrace();
}
}//GEN-LAST:event_BOTGeraHtmlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeraRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeraRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeraRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeraRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GeraRelatorio().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTGeraHtml;
    private javax.swing.JButton BOTGeraPdf;
    private javax.swing.JButton BOTVisualiza;
    // End of variables declaration//GEN-END:variables
public void abreRelatorioT2(){
    try{
    Connection con = new ConexaoSQL().getConnection();
    //HashMap parametros = new HashMap();
    //JasperReport jasperReport = (JasperReport) JRLoader.loadObject("C:/Java/ProjetoTCC/src/sys/taxi/com/all/impresao/RPTFuncionarios.jasper");    
    //JasperPrint jp = JasperFillManager.fillReport(/*jasperReport*/"C:/Java/ProjetoTCC/src/sys/taxi/com/all/impresao/RPTFuncionarios.jasper", new HashMap(), con);
    //JasperPrint jp = JasperFillManager.fillReport("./Relatorios/RLTTesteVazio.jasper", new HashMap(), con);
    JasperPrint jp = JasperFillManager.fillReport("./Relatorios/Aulas/Teste.jasper", new HashMap(), con);
    //JasperPrint jp = JasperFillManager.fillReport("./Relatorios/RPTFuncionarios.jasper", parametros, con);
    JasperViewer jrv = new JasperViewer(jp);
    jrv.setVisible(true);
}catch(Exception e){
    e.printStackTrace();
}
}

/*public void abreRelatorioNet(){
try{
Connection con = new ConexaoSQL().getConnection();
    JasperReport jasperReport = (JasperReport) JRLoader.loadObject("C:/Java/ProjetoTCC/src/sys/taxi/com/all/impresao/RPTFuncionarios.jasper");    
    JasperPrint jp = JasperFillManager.fillReport(jasperReport, new HashMap(), con);
    JasperViewer.viewReport(jp, false);
    //JasperViewer jrv = new JasperViewer(jp, false);
    //jrv.setVisible(true);
}catch(Exception e){
    e.printStackTrace();
}
    
}*/
}
