package sys.taxi.com.br.util;


import java.sql.Connection;


/*
 * GeraRelatorio.java
 *
 * Created on 14 de Setembro de 2008, 03:22
 */
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author  Cláudio
 */
public class GeraRelatorioT2 extends javax.swing.JFrame {

    /** Creates new form GeraRelatorio */
    public GeraRelatorioT2() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btVisualizar = new javax.swing.JButton();
        btGeraPDF = new javax.swing.JButton();
        btGeraHTML = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Curso JasperReports / iReport - T2Ti.com");

        btVisualizar.setText("Visualizar");
        btVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVisualizarActionPerformed(evt);
            }
        });

        btGeraPDF.setText("Gerar PDF");
        btGeraPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGeraPDFActionPerformed(evt);
            }
        });

        btGeraHTML.setText("Gerar HTML");
        btGeraHTML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGeraHTMLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btVisualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btGeraPDF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btGeraHTML)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVisualizar)
                    .addComponent(btGeraPDF)
                    .addComponent(btGeraHTML))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
Connection con;
private void btVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVisualizarActionPerformed
    try{
         con = new ConexaoSQL().getConnection();
        HashMap parametros = new HashMap();
        /*parametros.put("DATA_INICIO", "2007/07/01");
        parametros.put("DATA_FIM", "2007/07/10");*/
        //JasperPrint jp = JasperFillManager.fillReport("./Relatorios/RPTFuncionarios.jasper", parametros, con);
        JasperPrint jp = JasperFillManager.fillReport("./Relatorios/RLTTesteVazio.jasper", parametros, con);
        //C:\Java\ProjetoTCC\Relatorios\RLTTesteVazio.jasper
        JasperViewer jrv = new JasperViewer(jp);
        jrv.setVisible(true);
    }
    catch(Exception e){
        e.printStackTrace();
    }
}//GEN-LAST:event_btVisualizarActionPerformed

private void btGeraPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGeraPDFActionPerformed
    try{
        con = new ConexaoSQL().getConnection();
        HashMap parametros = new HashMap();
        JasperPrint jp = JasperFillManager.fillReport("./Relatorios/RPTFuncionarios.jasper", parametros, con);
        JasperExportManager.exportReportToPdfFile(jp, "./produtos.pdf");
    }
    catch(Exception e){
        e.printStackTrace();
    }
}//GEN-LAST:event_btGeraPDFActionPerformed

private void btGeraHTMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGeraHTMLActionPerformed
    try{
        con = new ConexaoSQL().getConnection();
        HashMap parametros = new HashMap();
        JasperPrint jp = JasperFillManager.fillReport("./jasper/Produtos.jasper", parametros, con);
        JasperExportManager.exportReportToHtmlFile(jp, "./produtos.html");
    }
    catch(Exception e){
        e.printStackTrace();
    }
}//GEN-LAST:event_btGeraHTMLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GeraRelatorioT2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGeraHTML;
    private javax.swing.JButton btGeraPDF;
    private javax.swing.JButton btVisualizar;
    // End of variables declaration//GEN-END:variables
}
