/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClienteView.java
 *
 * Created on 15/01/2013, 18:24:47
 */
package sys.taxi.com.br.view;


import br.com.adilson.util.PrinterMatrix;
import java.awt.EventQueue;
import java.beans.Beans;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import javax.persistence.RollbackException;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author VGCT
 */
public class ClienteView extends JPanel {
    
    public ClienteView(String pm) {
        initComponents();
        if (!Beans.isDesignTime()) {
            entityManager.getTransaction().begin();
        }
 //       guardaInformacoes tipoLogin = new guardaInformacoes();
        
        //String permicao = tipoLogin.getTipoLogin();
        
        if ("N".equals(pm)){
            Consulta.setVisible(false);
        }else{if("C".equals(pm)){
      ferramentaBotoes.setVisible(false);
        }else{
            
        }
            
        }
        
        botaoOculto(BOTRelatorio);
     BOTEditarEndereco.setVisible(false);   
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("taxiPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Cliente c");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        rowSorterToStringConverter1 = new sys.taxi.com.all.util.RowSorterToStringConverter();
        tabelaCliente = new javax.swing.JTabbedPane();
        Consulta = new javax.swing.JPanel();
        masterScrollPane = new javax.swing.JScrollPane();
        masterTable = new javax.swing.JTable();
        ferramentaBotoes = new javax.swing.JPanel();
        deleteButton = new javax.swing.JButton();
        BOTIncluirCliente = new javax.swing.JButton();
        BOTEditarCliente = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        EDIPesquisa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BOTRelatorio = new javax.swing.JButton();
        Cadastro = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        newDetailButton = new javax.swing.JButton();
        deleteDetailButton = new javax.swing.JButton();
        BOTEditarEndereco = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        detailScrollPane = new javax.swing.JScrollPane();
        detailTable = new javax.swing.JTable();
        Impressao = new javax.swing.JPanel();
        PainelImpresao = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        BOTImprimir2 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        folha = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        FormListener formListener = new FormListener();

        rowSorterToStringConverter1.setTable(masterTable);

        setLayout(null);

        tabelaCliente.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        masterTable.setAutoscrolls(false);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list, masterTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nomecli}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${emailcli}"));
        columnBinding.setColumnName("Email");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${telefonecli}"));
        columnBinding.setColumnName("Telefone");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${celularcli}"));
        columnBinding.setColumnName("Celular");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${datanascli}"));
        columnBinding.setColumnName("Data Nascimento");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${datacadastrocli}"));
        columnBinding.setColumnName("Data Cadastro");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        masterScrollPane.setViewportView(masterTable);
        masterTable.getColumnModel().getColumn(0).setPreferredWidth(200);
        masterTable.getColumnModel().getColumn(1).setPreferredWidth(200);
        masterTable.getColumnModel().getColumn(2).setMinWidth(90);
        masterTable.getColumnModel().getColumn(2).setPreferredWidth(95);
        masterTable.getColumnModel().getColumn(3).setPreferredWidth(95);
        masterTable.getColumnModel().getColumn(4).setPreferredWidth(100);
        masterTable.getColumnModel().getColumn(5).setPreferredWidth(100);

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/ico_excluir.gif"))); // NOI18N
        deleteButton.setText("Excluir Cliente");
        deleteButton.setToolTipText("Excuira o cliente da linha selecionada");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), deleteButton, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        deleteButton.addActionListener(formListener);

        BOTIncluirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/ico_adicionar.png"))); // NOI18N
        BOTIncluirCliente.setText("Incluir Cliente");
        BOTIncluirCliente.setToolTipText("Adicionará um cliente ao banco de dados");
        BOTIncluirCliente.addActionListener(formListener);

        BOTEditarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/ico_editar.png"))); // NOI18N
        BOTEditarCliente.setText("Editar Cliente");
        BOTEditarCliente.setToolTipText("Editara o cliente da linha selecionada");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), BOTEditarCliente, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        BOTEditarCliente.addActionListener(formListener);

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/ico_salvar.png"))); // NOI18N
        saveButton.setText("Salvar");
        saveButton.addActionListener(formListener);

        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/ico_atualiza.gif"))); // NOI18N
        refreshButton.setText("Atualizar");
        refreshButton.addActionListener(formListener);

        jButton1.setText("Cadastro de Endereço");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), jButton1, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jButton1.addActionListener(formListener);

        javax.swing.GroupLayout ferramentaBotoesLayout = new javax.swing.GroupLayout(ferramentaBotoes);
        ferramentaBotoes.setLayout(ferramentaBotoesLayout);
        ferramentaBotoesLayout.setHorizontalGroup(
            ferramentaBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ferramentaBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BOTIncluirCliente)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(BOTEditarCliente)
                .addGap(18, 18, 18)
                .addComponent(saveButton)
                .addGap(18, 18, 18)
                .addComponent(deleteButton)
                .addGap(18, 18, 18)
                .addComponent(refreshButton)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        ferramentaBotoesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BOTIncluirCliente, deleteButton});

        ferramentaBotoesLayout.setVerticalGroup(
            ferramentaBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ferramentaBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ferramentaBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BOTIncluirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(BOTEditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${rowSorter}"), EDIPesquisa, org.jdesktop.beansbinding.BeanProperty.create("text"), "");
        binding.setConverter(rowSorterToStringConverter1);
        bindingGroup.addBinding(binding);

        jLabel1.setText("Pesquisar :");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EDIPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(EDIPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        BOTRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/bot_relatorio 2.png"))); // NOI18N

        javax.swing.GroupLayout ConsultaLayout = new javax.swing.GroupLayout(Consulta);
        Consulta.setLayout(ConsultaLayout);
        ConsultaLayout.setHorizontalGroup(
            ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaLayout.createSequentialGroup()
                .addGroup(ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ConsultaLayout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(87, 87, 87)
                        .addComponent(BOTRelatorio))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ConsultaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ferramentaBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(ConsultaLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(masterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        ConsultaLayout.setVerticalGroup(
            ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(ferramentaBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConsultaLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ConsultaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BOTRelatorio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(masterScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addGap(144, 144, 144))
        );

        tabelaCliente.addTab("Consulta Cliente", Consulta);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        newDetailButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/ico_adicionar.png"))); // NOI18N
        newDetailButton.setText("Incluir Endereço");
        newDetailButton.setToolTipText("Incluira um endereço ao banco de dados");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), newDetailButton, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        newDetailButton.addActionListener(formListener);

        deleteDetailButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/ico_excluir.gif"))); // NOI18N
        deleteDetailButton.setText("Excluir Endereço");
        deleteDetailButton.setToolTipText("Excluira o endereço selecionado");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, detailTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), deleteDetailButton, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        deleteDetailButton.addActionListener(formListener);

        BOTEditarEndereco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/ico_editar.png"))); // NOI18N
        BOTEditarEndereco.setText("Editar Endereço");
        BOTEditarEndereco.setToolTipText("Editara o endereço selecionado");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, detailTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), BOTEditarEndereco, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        BOTEditarEndereco.addActionListener(formListener);

        jButton4.setText("Cadastro de Clientes");
        jButton4.addActionListener(formListener);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newDetailButton)
                .addGap(18, 18, 18)
                .addComponent(BOTEditarEndereco)
                .addGap(18, 18, 18)
                .addComponent(deleteDetailButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {deleteDetailButton, newDetailButton});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newDetailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BOTEditarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteDetailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${selectedElement.enderecocliCollection}");
        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, eLProperty, detailTable);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cepcli}"));
        columnBinding.setColumnName("CEP");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${ufcli}"));
        columnBinding.setColumnName("Uf");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cidadecli}"));
        columnBinding.setColumnName("Cidade");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${bairrocli}"));
        columnBinding.setColumnName("Bairro");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${enderecocli}"));
        columnBinding.setColumnName("Endereço");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${numerocasacli}"));
        columnBinding.setColumnName("Numero Casa");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${complementocli}"));
        columnBinding.setColumnName("Complemento");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        jTableBinding.setSourceUnreadableValue(java.util.Collections.emptyList());
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        detailScrollPane.setViewportView(detailTable);
        detailTable.getColumnModel().getColumn(0).setPreferredWidth(100);
        detailTable.getColumnModel().getColumn(1).setPreferredWidth(35);
        detailTable.getColumnModel().getColumn(2).setPreferredWidth(100);
        detailTable.getColumnModel().getColumn(3).setPreferredWidth(100);
        detailTable.getColumnModel().getColumn(4).setPreferredWidth(180);
        detailTable.getColumnModel().getColumn(5).setPreferredWidth(110);
        detailTable.getColumnModel().getColumn(6).setPreferredWidth(140);

        javax.swing.GroupLayout CadastroLayout = new javax.swing.GroupLayout(Cadastro);
        Cadastro.setLayout(CadastroLayout);
        CadastroLayout.setHorizontalGroup(
            CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroLayout.createSequentialGroup()
                .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastroLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(detailScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CadastroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        CadastroLayout.setVerticalGroup(
            CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(detailScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(195, Short.MAX_VALUE))
        );

        tabelaCliente.addTab("Consulta Endereço", Cadastro);

        BOTImprimir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/ico_impressora.png"))); // NOI18N
        BOTImprimir2.setText("Imprimir");
        BOTImprimir2.addActionListener(formListener);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 617, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );

        jButton2.setText("Cancelar Impresão");
        jButton2.addActionListener(formListener);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(512, Short.MAX_VALUE)
                .addComponent(BOTImprimir2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(196, 196, 196))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BOTImprimir2)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        PainelImpresao.addTab("Propriedades", jPanel10);

        jScrollPane4.setViewportView(folha);

        jButton3.setText("Voltar");
        jButton3.addActionListener(formListener);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 865, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(494, Short.MAX_VALUE))
        );

        PainelImpresao.addTab("Imprensao", jPanel12);

        javax.swing.GroupLayout ImpressaoLayout = new javax.swing.GroupLayout(Impressao);
        Impressao.setLayout(ImpressaoLayout);
        ImpressaoLayout.setHorizontalGroup(
            ImpressaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelImpresao, javax.swing.GroupLayout.DEFAULT_SIZE, 941, Short.MAX_VALUE)
        );
        ImpressaoLayout.setVerticalGroup(
            ImpressaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelImpresao, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
        );

        tabelaCliente.addTab("Impressao", Impressao);

        add(tabelaCliente);
        tabelaCliente.setBounds(0, 0, 946, 640);

        bindingGroup.bind();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == deleteButton) {
                ClienteView.this.deleteButtonActionPerformed(evt);
            }
            else if (evt.getSource() == BOTIncluirCliente) {
                ClienteView.this.newButtonActionPerformed(evt);
            }
            else if (evt.getSource() == BOTEditarCliente) {
                ClienteView.this.BOTEditarClienteActionPerformed(evt);
            }
            else if (evt.getSource() == saveButton) {
                ClienteView.this.saveButtonActionPerformed(evt);
            }
            else if (evt.getSource() == refreshButton) {
                ClienteView.this.refreshButtonActionPerformed(evt);
            }
            else if (evt.getSource() == jButton1) {
                ClienteView.this.jButton1ActionPerformed(evt);
            }
            else if (evt.getSource() == newDetailButton) {
                ClienteView.this.newDetailButtonActionPerformed(evt);
            }
            else if (evt.getSource() == deleteDetailButton) {
                ClienteView.this.deleteDetailButtonActionPerformed(evt);
            }
            else if (evt.getSource() == BOTEditarEndereco) {
                ClienteView.this.BOTEditarEnderecoActionPerformed(evt);
            }
            else if (evt.getSource() == jButton4) {
                ClienteView.this.jButton4ActionPerformed(evt);
            }
            else if (evt.getSource() == BOTImprimir2) {
                ClienteView.this.BOTImprimir2ActionPerformed(evt);
            }
            else if (evt.getSource() == jButton2) {
                ClienteView.this.jButton2ActionPerformed(evt);
            }
            else if (evt.getSource() == jButton3) {
                ClienteView.this.jButton3ActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

   
    private void deleteDetailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDetailButtonActionPerformed
        int index = masterTable.getSelectedRow();
        sys.taxi.com.br.bean.Cliente c = list.get(masterTable.convertRowIndexToModel(index));
        Collection<sys.taxi.com.br.bean.Enderecocli> es = c.getEnderecocliCollection();
        int[] selected = detailTable.getSelectedRows();
        List<sys.taxi.com.br.bean.Enderecocli> toRemove = new ArrayList<sys.taxi.com.br.bean.Enderecocli>(selected.length);
        for (int idx = 0; idx < selected.length; idx++) {
            selected[idx] = detailTable.convertRowIndexToModel(selected[idx]);
            int count = 0;
            Iterator<sys.taxi.com.br.bean.Enderecocli> iter = es.iterator();
            while (count++ < selected[idx]) {
                iter.next();
            }
            sys.taxi.com.br.bean.Enderecocli e = iter.next();
            toRemove.add(e);
            entityManager.remove(e);
        }
        es.removeAll(toRemove);
        masterTable.clearSelection();
        masterTable.setRowSelectionInterval(index, index);
    }//GEN-LAST:event_deleteDetailButtonActionPerformed
    
    private void newDetailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDetailButtonActionPerformed
        int index = masterTable.getSelectedRow();
        sys.taxi.com.br.bean.Cliente c = list.get(masterTable.convertRowIndexToModel(index));
        
        Collection<sys.taxi.com.br.bean.Enderecocli> es = c.getEnderecocliCollection();
        if (es == null) {
            es = new LinkedList<sys.taxi.com.br.bean.Enderecocli>();
            c.setEnderecocliCollection((List) es);
        }
        sys.taxi.com.br.bean.Enderecocli e = new sys.taxi.com.br.bean.Enderecocli();
        entityManager.persist(e);
        e.setCodcliente(c);
        es.add(e);
        masterTable.clearSelection();
        masterTable.setRowSelectionInterval(index, index);
        int row = es.size() - 1;
        detailTable.setRowSelectionInterval(row, row);
        detailTable.scrollRectToVisible(detailTable.getCellRect(row, 0, true));
        
        DialogClienteEnderecoView cev = new DialogClienteEnderecoView(null, true);
        
        String codClienteV = ""+e.getCodcliente();
        codClienteV = codClienteV.substring((codClienteV.indexOf("=")+1), (codClienteV.indexOf("]")-1));

        e.setCodigocliente(Integer.parseInt(codClienteV));
        
        
        cev.setRegistroAtual(e);
        cev.setLocationRelativeTo(null);
        cev.setVisible(true);
        
           if (cev.isConfirmaEndereco()){
            saveButton.doClick();
        }else{
            deleteDetailButton.doClick();
        }

        
    }//GEN-LAST:event_newDetailButtonActionPerformed
    

    @SuppressWarnings("unchecked")
    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        entityManager.getTransaction().rollback();
        entityManager.getTransaction().begin();
        java.util.Collection data = query.getResultList();
        for (Object entity : data) {
            entityManager.refresh(entity);
        }
        list.clear();
        list.addAll(data);
    }//GEN-LAST:event_refreshButtonActionPerformed
    
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int[] selected = masterTable.getSelectedRows();
        List<sys.taxi.com.br.bean.Cliente> toRemove = new ArrayList<sys.taxi.com.br.bean.Cliente>(selected.length);
        for (int idx = 0; idx < selected.length; idx++) {
            sys.taxi.com.br.bean.Cliente c = list.get(masterTable.convertRowIndexToModel(selected[idx]));
            toRemove.add(c);
            entityManager.remove(c);
        }
        list.removeAll(toRemove);
        
    }//GEN-LAST:event_deleteButtonActionPerformed
        
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            entityManager.getTransaction().commit();
            entityManager.getTransaction().begin();
        } catch (RollbackException rex) {
            rex.printStackTrace();
            entityManager.getTransaction().begin();
            List<sys.taxi.com.br.bean.Cliente> merged = new ArrayList<sys.taxi.com.br.bean.Cliente>(list.size());
            for (sys.taxi.com.br.bean.Cliente c : list) {
                merged.add(entityManager.merge(c));
                JOptionPane.showMessageDialog(null, "Não é possivel excluir o registro, certifique que este cliente nao esta sendo utilizado em outra tabela !");
                refreshButton.doClick();
            }
            list.clear();
            list.addAll(merged);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
         if (EDIPesquisa.getText() != null)
        {
            EDIPesquisa.setText("");
        }
        sys.taxi.com.br.bean.Cliente c = new sys.taxi.com.br.bean.Cliente();
        entityManager.persist(c);
        list.add(c);
        int row = list.size() - 1;
        masterTable.setRowSelectionInterval(row, row);
        masterTable.scrollRectToVisible(masterTable.getCellRect(row, 0, true));
        java.util.Date agora = new java.util.Date();
        c.setDatacadastrocli(agora);
        
        DialogClienteView cliCampos = new DialogClienteView(null, true);
        cliCampos.setDadoCliente(c);
        cliCampos.setLocationRelativeTo(null);
        cliCampos.setVisible(true);
        
        if (cliCampos.isConfirmaCliente()){
            saveButton.doClick();
        }else{
            refreshButton.doClick();
        }


}//GEN-LAST:event_newButtonActionPerformed

private void BOTEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTEditarClienteActionPerformed
DialogClienteView ce = new DialogClienteView(null, true);
        ce.setDadoCliente(list.get(masterTable.getSelectedRow()));
        ce.setLocationRelativeTo(null);
        ce.setVisible(true);  
        
        if (ce.isConfirmaCliente()){
            saveButton.doClick();
        }else{
            //refreshButton.doClick();
        }
}//GEN-LAST:event_BOTEditarClienteActionPerformed

private void BOTEditarEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTEditarEnderecoActionPerformed
DialogClienteEnderecoView cev = new DialogClienteEnderecoView(null, true);
    
sys.taxi.com.br.bean.Cliente c = list.get(detailTable.getSelectedRow()-1);

        //int index = masterTable.getSelectedRow();
        //sys.taxi.com.br.bean.Cliente c = list.get(masterTable.convertRowIndexToModel(index));
        //Collection<sys.taxi.com.br.bean.Enderecocli> es = c.getEnderecocliCollection();
    
    
//    cev.setRegistroAtual(es);
cev.setLocationRelativeTo(null);
cev.setVisible(true);
if(cev.isConfirmaEndereco()){
    saveButton.doClick();
}else{
    //refreshButton.doClick();
}

}//GEN-LAST:event_BOTEditarEnderecoActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
tabelaCliente.setSelectedIndex(1);
}//GEN-LAST:event_jButton1ActionPerformed

private void BOTImprimir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTImprimir2ActionPerformed
query = entityManager.createNamedQuery("Cliente.findAll");
        List<sys.taxi.com.br.bean.Cliente> clientes = query.getResultList();
    
    
PrinterMatrix printer=new PrinterMatrix();
printer.setOutSize( clientes.size() + 6, 70 );
printer.printCharAtCol( 1, 1, 70, "=" );
printer.printTextLinCol( 2, 1, printer.centralizar(70, "Sistema VGCT - Relatorio de Lucro de caixa"));//42

printer.printCharAtCol( 3, 1, 70, "*" );
printer.printTextLinCol( 4, 1, "Nome Cliente" );
printer.printTextLinCol( 4, 30, "| Celular" );
printer.printTextLinCol( 4, 48, "| Data Cadastro" );
printer.printCharAtCol( 5, 1, 70, "-" );    

int linha = 6;
for (sys.taxi.com.br.bean.Cliente cli : clientes){
    printer.printTextLinCol( linha, 1, cli.getNomecli());
    printer.printTextLinCol( linha, 30,"| "+ cli.getCelularcli());
    printer.printTextLinCol( linha, 48,"| "+ cli.getDatacadastrocli());
    printer.printCharAtCol(linha+1, 1, 60, "-");
    
    linha++;
    
}


printer.printCharAtCol( linha, 1, 70, "=" );    
printer.toImageFile("src/sys/taxi/com/all/Images/Imprensao/cliente.jpg");
    
    
            //areaRelatorio.setText(carregaArquivo("veiculos.txt"));
            //areaRelatorio.moveCaretPosition(0);
            //jLabel1.setIcon(new ImageIcon("src/veiculos.jpg"));
            folha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/Imprensao/cliente.jpg")));
        
    PainelImpresao.setSelectedIndex(1);
}//GEN-LAST:event_BOTImprimir2ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
tabelaCliente.setSelectedIndex(0);
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
tabelaCliente.setSelectedIndex(0);
PainelImpresao.setSelectedIndex(0);
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
tabelaCliente.setSelectedIndex(0);
}//GEN-LAST:event_jButton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTEditarCliente;
    private javax.swing.JButton BOTEditarEndereco;
    private javax.swing.JButton BOTImprimir2;
    private javax.swing.JButton BOTIncluirCliente;
    private javax.swing.JButton BOTRelatorio;
    private javax.swing.JPanel Cadastro;
    private javax.swing.JPanel Consulta;
    private javax.swing.JTextField EDIPesquisa;
    private javax.swing.JPanel Impressao;
    private javax.swing.JTabbedPane PainelImpresao;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton deleteDetailButton;
    private javax.swing.JScrollPane detailScrollPane;
    private javax.swing.JTable detailTable;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JPanel ferramentaBotoes;
    private javax.swing.JLabel folha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane4;
    private java.util.List<sys.taxi.com.br.bean.Cliente> list;
    private javax.swing.JScrollPane masterScrollPane;
    private javax.swing.JTable masterTable;
    private javax.swing.JButton newDetailButton;
    private javax.persistence.Query query;
    private javax.swing.JButton refreshButton;
    private sys.taxi.com.all.util.RowSorterToStringConverter rowSorterToStringConverter1;
    private javax.swing.JButton saveButton;
    private javax.swing.JTabbedPane tabelaCliente;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    public static void main(final String[] args,final String cli) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {

            public void run() {
                JFrame frame = new JFrame();
                frame.setContentPane(new ClienteView(cli));
                frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                frame.pack();
                frame.setVisible(true);
                frame.setTitle(args[0]);
            }
        });
    }
    
    
    private void atualizaCliente(){
    
}

    private void botaoOculto(JButton botao){
            botao.setBorderPainted(false); 
            botao.setContentAreaFilled(false); 
            botao.setFocusPainted(false);             
}
    
}
