/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DiariaView.java
 *
 * Created on 21/01/2013, 18:06:50
 */
package sys.taxi.com.br.view;

import br.com.adilson.util.PrinterMatrix;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.beans.Beans;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import javax.persistence.RollbackException;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import sys.taxi.com.br.bean.Diariafunc;
import sys.taxi.com.br.bean.Funcionario;

/**
 *
 * @author VGCT
 */
public class DiariaView extends JPanel {

    public DiariaView(String da) {
        initComponents();
        if (!Beans.isDesignTime()) {
            entityManager.getTransaction().begin();
        }
        this.setPreferredSize(new Dimension(801, 536));
        DadosVistoria.setBackground(new Color(0, 0, 0, 0));
        //DadosBotaoVistoria.setBackground(new Color(0,0,0,0));
        if ("C".equals(da)){
            ControleFerramenta.setVisible(false);
        }else{
            ControleFerramenta.setVisible(true);
        }
        botaoOculto(BOTRelatorio);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("taxiPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT d FROM Diariafunc d");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        rowSorterToStringConverter1 = new sys.taxi.com.all.util.RowSorterToStringConverter();
        funcionarioQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT f FROM Funcionario f");
        funcionarioList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : funcionarioQuery.getResultList();
        veiculoQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT v FROM Veiculo v");
        veiculoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : veiculoQuery.getResultList();
        unidadeListCellRendererVeiculo1 = new sys.taxi.com.all.renderer.UnidadeListCellRendererVeiculo();
        unidadeListCellRendererFuncionario1 = new sys.taxi.com.all.renderer.UnidadeListCellRendererFuncionario();
        exibicaoTerminados = new javax.swing.ButtonGroup();
        lacoFunc = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(funcionarioQuery.getResultList());
        lacoVeiculo = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(veiculoQuery.getResultList());
        tabelaDiaria = new javax.swing.JTabbedPane();
        Consulta = new javax.swing.JPanel();
        ControleFerramenta = new javax.swing.JPanel();
        FerramentaBotoes = new javax.swing.JToolBar();
        Botoes = new javax.swing.JPanel();
        newButton = new javax.swing.JButton();
        BOTEditar = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        BOTControleVistoria = new javax.swing.JButton();
        masterScrollPane = new javax.swing.JScrollPane();
        masterTable = new javax.swing.JTable();
        Pesquisa = new javax.swing.JPanel();
        EDIPesquisar = new javax.swing.JTextField();
        TEXEditar = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        BOTFiltrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        EDIDe = new javax.swing.JTextField();
        EDIAte = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        RBTTerminados = new javax.swing.JRadioButton();
        RBTNaoTerminados = new javax.swing.JRadioButton();
        RBTTodos = new javax.swing.JRadioButton();
        BOTFinalizarTrabalho = new javax.swing.JButton();
        BOTRelatorio = new javax.swing.JButton();
        CadastroDiaria = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        EDIDataTrabalho = new javax.swing.JFormattedTextField();
        EDIHoraInicio = new javax.swing.JFormattedTextField();
        EDIHoraTermino = new javax.swing.JFormattedTextField();
        CBXSituacao = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        CBXLocal = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        BOTSalvar = new javax.swing.JButton();
        BOTCancelar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CBXVeiculo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        CBXFuncionario = new javax.swing.JComboBox();
        Vistoria = new javax.swing.JPanel();
        detailScrollPane = new javax.swing.JScrollPane();
        detailTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        deleteDetailButton = new javax.swing.JButton();
        newDetailButton = new javax.swing.JButton();
        BOTSalvarVistoria = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        CadastroVistoria = new javax.swing.JPanel();
        DadosVistoria = new javax.swing.JPanel();
        TEXDescricao = new javax.swing.JLabel();
        TEXLocalVistoria = new javax.swing.JLabel();
        TEXExtras = new javax.swing.JLabel();
        TEXObservacao = new javax.swing.JLabel();
        EDIDescricao = new javax.swing.JTextField();
        EDILocalVistoria = new javax.swing.JTextField();
        EDIExtras = new javax.swing.JTextField();
        EDIObservacao = new javax.swing.JTextField();
        DadosBotaoVistoria = new javax.swing.JPanel();
        BOTSalvar1 = new javax.swing.JButton();
        BOTCancela = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Impressao = new javax.swing.JPanel();
        PainelImpresao = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        BOTImprimir2 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        folha = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        FormListener formListener = new FormListener();

        rowSorterToStringConverter1.setTable(masterTable);

        unidadeListCellRendererVeiculo1.setText("unidadeListCellRendererVeiculo1");

        unidadeListCellRendererFuncionario1.setText("unidadeListCellRendererFuncionario1");

        setLayout(null);

        tabelaDiaria.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        FerramentaBotoes.setRollover(true);

        newButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/ico_adicionar.png"))); // NOI18N
        newButton.setText("Incluir");
        newButton.addActionListener(formListener);

        BOTEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/ico_editar.png"))); // NOI18N
        BOTEditar.setText("Editar");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), BOTEditar, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        BOTEditar.addActionListener(formListener);

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/ico_excluir.gif"))); // NOI18N
        deleteButton.setText("Excluir");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), deleteButton, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        deleteButton.addActionListener(formListener);

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/ico_salvar.png"))); // NOI18N
        saveButton.setText("Salvar");
        saveButton.addActionListener(formListener);

        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/ico_atualiza.gif"))); // NOI18N
        refreshButton.setText("Atualizar");
        refreshButton.addActionListener(formListener);

        BOTControleVistoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/ico_pesquisaRoda2.png"))); // NOI18N
        BOTControleVistoria.setText("Fazer Vistoria");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), BOTControleVistoria, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        BOTControleVistoria.addActionListener(formListener);

        javax.swing.GroupLayout BotoesLayout = new javax.swing.GroupLayout(Botoes);
        Botoes.setLayout(BotoesLayout);
        BotoesLayout.setHorizontalGroup(
            BotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newButton)
                .addGap(18, 18, 18)
                .addComponent(BOTEditar)
                .addGap(18, 18, 18)
                .addComponent(deleteButton)
                .addGap(18, 18, 18)
                .addComponent(refreshButton)
                .addGap(18, 18, 18)
                .addComponent(saveButton)
                .addGap(18, 18, 18)
                .addComponent(BOTControleVistoria, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );

        BotoesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {deleteButton, newButton});

        BotoesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {refreshButton, saveButton});

        BotoesLayout.setVerticalGroup(
            BotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BOTEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BOTControleVistoria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        FerramentaBotoes.add(Botoes);

        javax.swing.GroupLayout ControleFerramentaLayout = new javax.swing.GroupLayout(ControleFerramenta);
        ControleFerramenta.setLayout(ControleFerramentaLayout);
        ControleFerramentaLayout.setHorizontalGroup(
            ControleFerramentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 772, Short.MAX_VALUE)
            .addGroup(ControleFerramentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ControleFerramentaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(FerramentaBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        ControleFerramentaLayout.setVerticalGroup(
            ControleFerramentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(ControleFerramentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ControleFerramentaLayout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(FerramentaBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list, masterTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codfunc.nomefunc}"));
        columnBinding.setColumnName("Funcionario");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codveiculo.nomevei}"));
        columnBinding.setColumnName("Veiculo");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${situacaoDiaria}"));
        columnBinding.setColumnName("Situacao Diaria");
        columnBinding.setColumnClass(Character.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${localcorrida}"));
        columnBinding.setColumnName("Localcorrida");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${datatrabalho}"));
        columnBinding.setColumnName("Datatrabalho");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${horainicio}"));
        columnBinding.setColumnName("Horainicio");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${horatermino}"));
        columnBinding.setColumnName("Horatermino");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${situacaoCorrida}"));
        columnBinding.setColumnName("Situação Corrida");
        columnBinding.setColumnClass(Character.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        masterScrollPane.setViewportView(masterTable);

        Pesquisa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${rowSorter}"), EDIPesquisar, org.jdesktop.beansbinding.BeanProperty.create("text"), "");
        binding.setConverter(rowSorterToStringConverter1);
        bindingGroup.addBinding(binding);

        TEXEditar.setText("Pesquisar :");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Exibir Entre"));

        BOTFiltrar.setText("Filtrar");
        BOTFiltrar.addActionListener(formListener);

        jLabel7.setText("De");

        jLabel8.setText("a :");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EDIDe, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EDIAte, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BOTFiltrar)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(BOTFiltrar)
                    .addComponent(EDIDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EDIAte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout PesquisaLayout = new javax.swing.GroupLayout(Pesquisa);
        Pesquisa.setLayout(PesquisaLayout);
        PesquisaLayout.setHorizontalGroup(
            PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TEXEditar)
                .addGap(18, 18, 18)
                .addComponent(EDIPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PesquisaLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        PesquisaLayout.setVerticalGroup(
            PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TEXEditar)
                    .addComponent(EDIPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Exibir Por"));

        exibicaoTerminados.add(RBTTerminados);
        RBTTerminados.setText("Inativos");
        RBTTerminados.addItemListener(formListener);

        exibicaoTerminados.add(RBTNaoTerminados);
        RBTNaoTerminados.setText("Ativos");
        RBTNaoTerminados.addItemListener(formListener);

        exibicaoTerminados.add(RBTTodos);
        RBTTodos.setText("Todos");
        RBTTodos.addItemListener(formListener);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RBTNaoTerminados)
                    .addComponent(RBTTerminados)
                    .addComponent(RBTTodos))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(RBTNaoTerminados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RBTTerminados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RBTTodos)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        BOTFinalizarTrabalho.setText("Finalizar Trabalho");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), BOTFinalizarTrabalho, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        BOTFinalizarTrabalho.addActionListener(formListener);

        BOTRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/bot_relatorio 2.png"))); // NOI18N

        javax.swing.GroupLayout ConsultaLayout = new javax.swing.GroupLayout(Consulta);
        Consulta.setLayout(ConsultaLayout);
        ConsultaLayout.setHorizontalGroup(
            ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaLayout.createSequentialGroup()
                .addGroup(ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConsultaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ControleFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ConsultaLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ConsultaLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(masterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ConsultaLayout.createSequentialGroup()
                        .addGap(719, 719, 719)
                        .addGroup(ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BOTRelatorio)
                            .addComponent(BOTFinalizarTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        ConsultaLayout.setVerticalGroup(
            ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ControleFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConsultaLayout.createSequentialGroup()
                        .addGroup(ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ConsultaLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(BOTRelatorio)))
                        .addGap(11, 11, 11)
                        .addComponent(BOTFinalizarTrabalho))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(masterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        tabelaDiaria.addTab("Diaria", Consulta);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Data Trabalho :");

        jLabel4.setText("Hora inicio :");

        jLabel5.setText("Hora Termino :");

        jLabel6.setText("Situação Corrida:");

        EDIDataTrabalho.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.datatrabalho}"), EDIDataTrabalho, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), EDIDataTrabalho, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        EDIHoraInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.horainicio}"), EDIHoraInicio, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), EDIHoraInicio, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        EDIHoraTermino.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.horatermino}"), EDIHoraTermino, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), EDIHoraTermino, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        EDIHoraTermino.addActionListener(formListener);

        CBXSituacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Ativo", "Inativo" }));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.situacao}"), CBXSituacao, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), CBXSituacao, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jLabel15.setText("Local:");

        CBXLocal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Região 1", "Região 2" }));

        BOTSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/ico_salvar.png"))); // NOI18N
        BOTSalvar.setText("Salvar");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), BOTSalvar, org.jdesktop.beansbinding.BeanProperty.create("doubleBuffered"));
        bindingGroup.addBinding(binding);

        BOTSalvar.addActionListener(formListener);

        BOTCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/ico_excluir.gif"))); // NOI18N
        BOTCancelar.setText("Cancelar");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), BOTCancelar, org.jdesktop.beansbinding.BeanProperty.create("doubleBuffered"));
        bindingGroup.addBinding(binding);

        BOTCancelar.addActionListener(formListener);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BOTSalvar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BOTCancelar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BOTSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BOTCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Funcionario :");

        CBXVeiculo.setRenderer(unidadeListCellRendererVeiculo1);

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, veiculoList, CBXVeiculo);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.codveiculo}"), CBXVeiculo, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), CBXVeiculo, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        CBXVeiculo.addFocusListener(formListener);

        jLabel2.setText("Veiculo :");

        CBXFuncionario.setRenderer(unidadeListCellRendererFuncionario1);

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, funcionarioList, CBXFuncionario);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.codfunc}"), CBXFuncionario, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(CBXFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(CBXVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CBXFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(CBXVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(CBXLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(CBXSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(280, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(EDIHoraTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(273, 273, 273))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(EDIDataTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(EDIHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(CBXLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(CBXSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(EDIDataTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(EDIHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(EDIHoraTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout CadastroDiariaLayout = new javax.swing.GroupLayout(CadastroDiaria);
        CadastroDiaria.setLayout(CadastroDiariaLayout);
        CadastroDiariaLayout.setHorizontalGroup(
            CadastroDiariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroDiariaLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        CadastroDiariaLayout.setVerticalGroup(
            CadastroDiariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroDiariaLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        tabelaDiaria.addTab("Cadastro", CadastroDiaria);

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${selectedElement.vistoriadiariaList}");
        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, eLProperty, detailTable);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${localvistoria}"));
        columnBinding.setColumnName("Localvistoria");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${descricao}"));
        columnBinding.setColumnName("Descricao");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${extras}"));
        columnBinding.setColumnName("Extras");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${observacao}"));
        columnBinding.setColumnName("Observacao");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        jTableBinding.setSourceUnreadableValue(java.util.Collections.emptyList());
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        detailScrollPane.setViewportView(detailTable);

        deleteDetailButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/ico_excluir.gif"))); // NOI18N
        deleteDetailButton.setText("Excluir Vistoria");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, detailTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), deleteDetailButton, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        deleteDetailButton.addActionListener(formListener);

        newDetailButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/ico_adicionar.png"))); // NOI18N
        newDetailButton.setText("Nova Vistoria");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), newDetailButton, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        newDetailButton.addActionListener(formListener);

        BOTSalvarVistoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/ico_salvar.png"))); // NOI18N
        BOTSalvarVistoria.setText("Salvar");
        BOTSalvarVistoria.addActionListener(formListener);

        jButton1.setText("Terminar Vistoria");
        jButton1.addActionListener(formListener);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newDetailButton)
                .addGap(18, 18, 18)
                .addComponent(deleteDetailButton)
                .addGap(18, 18, 18)
                .addComponent(BOTSalvarVistoria)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newDetailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteDetailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BOTSalvarVistoria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/Gasolina.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/Chave de fendas.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/Chaves Mecanica.png"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/Motors.png"))); // NOI18N

        javax.swing.GroupLayout VistoriaLayout = new javax.swing.GroupLayout(Vistoria);
        Vistoria.setLayout(VistoriaLayout);
        VistoriaLayout.setHorizontalGroup(
            VistoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VistoriaLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(detailScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(31, 31, 31))
            .addGroup(VistoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VistoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VistoriaLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(172, 172, 172))
                    .addGroup(VistoriaLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 324, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(455, 455, 455))))
        );
        VistoriaLayout.setVerticalGroup(
            VistoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VistoriaLayout.createSequentialGroup()
                .addGroup(VistoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VistoriaLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(VistoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(VistoriaLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VistoriaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                                .addComponent(jLabel13))))
                    .addGroup(VistoriaLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(detailScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VistoriaLayout.createSequentialGroup()
                .addContainerGap(323, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(232, 232, 232))
        );

        tabelaDiaria.addTab("Vistoria", Vistoria);

        CadastroVistoria.setLayout(null);

        DadosVistoria.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        TEXDescricao.setText("Descrição :");

        TEXLocalVistoria.setText("Local Vistoria :");

        TEXExtras.setText("Extras :");

        TEXObservacao.setText("Observação :");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, detailTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.descricao}"), EDIDescricao, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, detailTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.localvistoria}"), EDILocalVistoria, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, detailTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.extras}"), EDIExtras, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, detailTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.observacao}"), EDIObservacao, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout DadosVistoriaLayout = new javax.swing.GroupLayout(DadosVistoria);
        DadosVistoria.setLayout(DadosVistoriaLayout);
        DadosVistoriaLayout.setHorizontalGroup(
            DadosVistoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DadosVistoriaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(DadosVistoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TEXLocalVistoria)
                    .addComponent(TEXDescricao)
                    .addComponent(TEXExtras)
                    .addComponent(TEXObservacao))
                .addGap(33, 33, 33)
                .addGroup(DadosVistoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EDIObservacao, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addComponent(EDIExtras, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addComponent(EDIDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addComponent(EDILocalVistoria, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );
        DadosVistoriaLayout.setVerticalGroup(
            DadosVistoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DadosVistoriaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(DadosVistoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TEXDescricao)
                    .addComponent(EDIDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(DadosVistoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TEXLocalVistoria)
                    .addComponent(EDILocalVistoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(DadosVistoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TEXExtras)
                    .addComponent(EDIExtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(DadosVistoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TEXObservacao)
                    .addComponent(EDIObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        CadastroVistoria.add(DadosVistoria);
        DadosVistoria.setBounds(270, 120, 420, 260);

        BOTSalvar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/ico_salvar.png"))); // NOI18N
        BOTSalvar1.setText("Salvar");
        BOTSalvar1.addActionListener(formListener);

        BOTCancela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/ico_excluir.gif"))); // NOI18N
        BOTCancela.setText("Cancelar");
        BOTCancela.addActionListener(formListener);

        javax.swing.GroupLayout DadosBotaoVistoriaLayout = new javax.swing.GroupLayout(DadosBotaoVistoria);
        DadosBotaoVistoria.setLayout(DadosBotaoVistoriaLayout);
        DadosBotaoVistoriaLayout.setHorizontalGroup(
            DadosBotaoVistoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
            .addGroup(DadosBotaoVistoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DadosBotaoVistoriaLayout.createSequentialGroup()
                    .addGap(0, 3, Short.MAX_VALUE)
                    .addComponent(BOTSalvar1)
                    .addGap(18, 18, 18)
                    .addComponent(BOTCancela)
                    .addGap(0, 3, Short.MAX_VALUE)))
        );
        DadosBotaoVistoriaLayout.setVerticalGroup(
            DadosBotaoVistoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(DadosBotaoVistoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DadosBotaoVistoriaLayout.createSequentialGroup()
                    .addGap(0, 5, Short.MAX_VALUE)
                    .addGroup(DadosBotaoVistoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BOTSalvar1)
                        .addComponent(BOTCancela))
                    .addGap(0, 6, Short.MAX_VALUE)))
        );

        CadastroVistoria.add(DadosBotaoVistoria);
        DadosBotaoVistoria.setBounds(440, 380, 210, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/Lexus-LFA_2011_800x600_wallpaper_34.png"))); // NOI18N
        CadastroVistoria.add(jLabel9);
        jLabel9.setBounds(320, 110, 390, 260);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/CarRepair-icon.png"))); // NOI18N
        CadastroVistoria.add(jLabel10);
        jLabel10.setBounds(0, -10, 256, 256);

        tabelaDiaria.addTab("Cadastro", CadastroVistoria);

        BOTImprimir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/ico_impressora.png"))); // NOI18N
        BOTImprimir2.setText("Imprimir");
        BOTImprimir2.addActionListener(formListener);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 617, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );

        jButton2.setText("Cancelar Impresão");
        jButton2.addActionListener(formListener);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(238, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(510, Short.MAX_VALUE)
                .addComponent(BOTImprimir2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(186, 186, 186))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BOTImprimir2)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        PainelImpresao.addTab("Propriedades", jPanel10);

        jScrollPane2.setViewportView(folha);

        jButton3.setText("Voltar");
        jButton3.addActionListener(formListener);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(505, Short.MAX_VALUE))
        );

        PainelImpresao.addTab("Imprensao", jPanel12);

        javax.swing.GroupLayout ImpressaoLayout = new javax.swing.GroupLayout(Impressao);
        Impressao.setLayout(ImpressaoLayout);
        ImpressaoLayout.setHorizontalGroup(
            ImpressaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelImpresao, javax.swing.GroupLayout.DEFAULT_SIZE, 929, Short.MAX_VALUE)
        );
        ImpressaoLayout.setVerticalGroup(
            ImpressaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelImpresao, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
        );

        tabelaDiaria.addTab("Impressao", Impressao);

        add(tabelaDiaria);
        tabelaDiaria.setBounds(0, 0, 934, 651);

        bindingGroup.bind();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, java.awt.event.FocusListener, java.awt.event.ItemListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == newButton) {
                DiariaView.this.newButtonActionPerformed(evt);
            }
            else if (evt.getSource() == BOTEditar) {
                DiariaView.this.BOTEditarActionPerformed(evt);
            }
            else if (evt.getSource() == deleteButton) {
                DiariaView.this.deleteButtonActionPerformed(evt);
            }
            else if (evt.getSource() == saveButton) {
                DiariaView.this.saveButtonActionPerformed(evt);
            }
            else if (evt.getSource() == refreshButton) {
                DiariaView.this.refreshButtonActionPerformed(evt);
            }
            else if (evt.getSource() == BOTControleVistoria) {
                DiariaView.this.BOTControleVistoriaActionPerformed(evt);
            }
            else if (evt.getSource() == BOTFiltrar) {
                DiariaView.this.BOTFiltrarActionPerformed(evt);
            }
            else if (evt.getSource() == BOTFinalizarTrabalho) {
                DiariaView.this.BOTFinalizarTrabalhoActionPerformed(evt);
            }
            else if (evt.getSource() == EDIHoraTermino) {
                DiariaView.this.EDIHoraTerminoActionPerformed(evt);
            }
            else if (evt.getSource() == BOTSalvar) {
                DiariaView.this.BOTSalvarActionPerformed(evt);
            }
            else if (evt.getSource() == BOTCancelar) {
                DiariaView.this.BOTCancelarActionPerformed(evt);
            }
            else if (evt.getSource() == deleteDetailButton) {
                DiariaView.this.deleteDetailButtonActionPerformed(evt);
            }
            else if (evt.getSource() == newDetailButton) {
                DiariaView.this.newDetailButtonActionPerformed(evt);
            }
            else if (evt.getSource() == BOTSalvarVistoria) {
                DiariaView.this.BOTSalvarVistoriaActionPerformed(evt);
            }
            else if (evt.getSource() == jButton1) {
                DiariaView.this.jButton1ActionPerformed(evt);
            }
            else if (evt.getSource() == BOTSalvar1) {
                DiariaView.this.BOTSalvar1ActionPerformed(evt);
            }
            else if (evt.getSource() == BOTCancela) {
                DiariaView.this.BOTCancelaActionPerformed(evt);
            }
            else if (evt.getSource() == BOTImprimir2) {
                DiariaView.this.BOTImprimir2ActionPerformed(evt);
            }
            else if (evt.getSource() == jButton2) {
                DiariaView.this.jButton2ActionPerformed(evt);
            }
            else if (evt.getSource() == jButton3) {
                DiariaView.this.jButton3ActionPerformed(evt);
            }
        }

        public void focusGained(java.awt.event.FocusEvent evt) {
        }

        public void focusLost(java.awt.event.FocusEvent evt) {
            if (evt.getSource() == CBXVeiculo) {
                DiariaView.this.CBXVeiculoFocusLost(evt);
            }
        }

        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            if (evt.getSource() == RBTTerminados) {
                DiariaView.this.RBTTerminadosItemStateChanged(evt);
            }
            else if (evt.getSource() == RBTNaoTerminados) {
                DiariaView.this.RBTNaoTerminadosItemStateChanged(evt);
            }
            else if (evt.getSource() == RBTTodos) {
                DiariaView.this.RBTTodosItemStateChanged(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void deleteDetailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDetailButtonActionPerformed
        int index = masterTable.getSelectedRow();
        sys.taxi.com.br.bean.Diariafunc d = list.get(masterTable.convertRowIndexToModel(index));
        Collection<sys.taxi.com.br.bean.Vistoriadiaria> vs = d.getVistoriadiariaList();
        int[] selected = detailTable.getSelectedRows();
        List<sys.taxi.com.br.bean.Vistoriadiaria> toRemove = new ArrayList<sys.taxi.com.br.bean.Vistoriadiaria>(selected.length);
        for (int idx = 0; idx < selected.length; idx++) {
            selected[idx] = detailTable.convertRowIndexToModel(selected[idx]);
            int count = 0;
            Iterator<sys.taxi.com.br.bean.Vistoriadiaria> iter = vs.iterator();
            while (count++ < selected[idx]) {
                iter.next();
            }
            sys.taxi.com.br.bean.Vistoriadiaria v = iter.next();
            toRemove.add(v);
            entityManager.remove(v);
        }
        vs.removeAll(toRemove);
        masterTable.clearSelection();
        masterTable.setRowSelectionInterval(index, index);
    }//GEN-LAST:event_deleteDetailButtonActionPerformed

    private void newDetailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDetailButtonActionPerformed
        int index = masterTable.getSelectedRow();
        sys.taxi.com.br.bean.Diariafunc d = list.get(masterTable.convertRowIndexToModel(index));
        Collection<sys.taxi.com.br.bean.Vistoriadiaria> vs = d.getVistoriadiariaList();
        if (vs == null) {
            vs = new LinkedList<sys.taxi.com.br.bean.Vistoriadiaria>();
            d.setVistoriadiariaList((List) vs);
        }
        sys.taxi.com.br.bean.Vistoriadiaria v = new sys.taxi.com.br.bean.Vistoriadiaria();
        entityManager.persist(v);
        v.setCoddiariafunc(d);
        vs.add(v);
        masterTable.clearSelection();
        masterTable.setRowSelectionInterval(index, index);
        int row = vs.size() - 1;
        detailTable.setRowSelectionInterval(row, row);
        detailTable.scrollRectToVisible(detailTable.getCellRect(row, 0, true));

        v.setAutomovel("" + d.getCodveiculo().getCodveiculo());

        tabelaDiaria.setSelectedIndex(3);
    }//GEN-LAST:event_newDetailButtonActionPerformed

    @SuppressWarnings("unchecked")
    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        voltandoDadosTabelaInicial();
        entityManager.getTransaction().rollback();
        entityManager.getTransaction().begin();
        java.util.Collection data = query.getResultList();
        for (Object entity : data) {
            entityManager.refresh(entity);
        }
        list.clear();
        list.addAll(data);
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int[] selected = masterTable.getSelectedRows();
        List<sys.taxi.com.br.bean.Diariafunc> toRemove = new ArrayList<sys.taxi.com.br.bean.Diariafunc>(selected.length);
        for (int idx = 0; idx < selected.length; idx++) {
            sys.taxi.com.br.bean.Diariafunc d = list.get(masterTable.convertRowIndexToModel(selected[idx]));
            toRemove.add(d);
            entityManager.remove(d);
        }
        list.removeAll(toRemove);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        atualizaDiariaInsere();
        if (funcionarioList.size() > 0){
        if (EDIPesquisar.getText() != null) {
            EDIPesquisar.setText("");
        }
        sys.taxi.com.br.bean.Diariafunc d = new sys.taxi.com.br.bean.Diariafunc();
        entityManager.persist(d);
        list.add(d);
        int row = list.size() - 1;
        masterTable.setRowSelectionInterval(row, row);
        masterTable.scrollRectToVisible(masterTable.getCellRect(row, 0, true));
        tabelaDiaria.setSelectedIndex(1);
        java.util.Date agora = new java.util.Date();
        EDIDataTrabalho.setValue(agora);
        EDIHoraInicio.setValue(agora);
        d.setSituacaoDiaria('S');
        d.setSituacaoCorrida('N');
        }else{
            JOptionPane.showMessageDialog(null, "Todos os funcionarios estão trabalhando","Falta Funcionarios",2);
        }
        CBXSituacao.setSelectedItem("Ativo");
    }//GEN-LAST:event_newButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        sys.taxi.com.br.bean.Diariafunc df = list.get(masterTable.getSelectedRow());
        try {
            entityManager.getTransaction().commit();
            entityManager.getTransaction().begin();
        } catch (RollbackException rex) {
            rex.printStackTrace();
            entityManager.getTransaction().begin();
            List<sys.taxi.com.br.bean.Diariafunc> merged = new ArrayList<sys.taxi.com.br.bean.Diariafunc>(list.size());
            for (sys.taxi.com.br.bean.Diariafunc d : list) {
                merged.add(entityManager.merge(d));
            }
            list.clear();
            list.addAll(merged);
        }

    }//GEN-LAST:event_saveButtonActionPerformed

private void BOTEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTEditarActionPerformed
    atualizaDiariaInsere();
    sys.taxi.com.br.bean.Diariafunc d = list.get(masterTable.getSelectedRow());
    //CBXSituacao.setSelectedItem("" + d.getSituacaoDiaria());
    if ("R1".equals(d.getLocalcorrida())){
        CBXLocal.setSelectedItem("Região 1");
    }else{if("R2".equals(d.getLocalcorrida())){
        CBXLocal.setSelectedItem("Região 2");
    }}
    
    if (d.getSituacaoDiaria() == 'S'){
        CBXSituacao.setSelectedItem("Ativo");
    }else{if(d.getSituacaoDiaria() == 'N'){
        CBXSituacao.setSelectedItem("Inativo");
    }}

    tabelaDiaria.setSelectedIndex(1);
}//GEN-LAST:event_BOTEditarActionPerformed

private void BOTCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTCancelarActionPerformed
    refreshButton.doClick();
    if (EDIPesquisar.getText() != null) {
        EDIPesquisar.setText("");
    }
    tabelaDiaria.setSelectedIndex(0);
}//GEN-LAST:event_BOTCancelarActionPerformed

private void BOTSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTSalvarActionPerformed
    sys.taxi.com.br.bean.Diariafunc df = list.get(masterTable.getSelectedRow());
    if (CBXLocal.getSelectedItem() ==  "Região 1"){
        df.setLocalcorrida("R1");
    }else{if(CBXLocal.getSelectedItem() ==  "Região 2"){
        df.setLocalcorrida("R2");
    }else{
        JOptionPane.showMessageDialog(null, "Selecione um Local!");
    }
    }
    
    if (CBXSituacao.getSelectedItem() ==  "Ativo"){
        df.setSituacaoCorrida('S');
    }else{if(CBXLocal.getSelectedItem() ==  "Inativo"){
        df.setSituacaoCorrida('N');
    }else{
        JOptionPane.showMessageDialog(null, "Insira um tipo de situação!");
    }
    }
    
    saveButton.doClick();
    tabelaDiaria.setSelectedIndex(0);
}//GEN-LAST:event_BOTSalvarActionPerformed

private void BOTControleVistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTControleVistoriaActionPerformed
    tabelaDiaria.setSelectedIndex(2);
}//GEN-LAST:event_BOTControleVistoriaActionPerformed

private void EDIHoraTerminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDIHoraTerminoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_EDIHoraTerminoActionPerformed

private void BOTSalvarVistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTSalvarVistoriaActionPerformed
    saveButton.doClick();
}//GEN-LAST:event_BOTSalvarVistoriaActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    tabelaDiaria.setSelectedIndex(0);
}//GEN-LAST:event_jButton1ActionPerformed

private void BOTSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTSalvar1ActionPerformed
//sys.taxi.com.br.bean.Diariafunc df = list.get(masterTable.getSelectedRow());
//df.get
    saveButton.doClick();
    tabelaDiaria.setSelectedIndex(2);
}//GEN-LAST:event_BOTSalvar1ActionPerformed

private void BOTCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTCancelaActionPerformed
//refreshButton.doClick();
    deleteDetailButton.doClick();
    tabelaDiaria.setSelectedIndex(2);
}//GEN-LAST:event_BOTCancelaActionPerformed

private void BOTFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTFiltrarActionPerformed
    exibicaoTerminados.clearSelection();
    if (EDIDe.getText().equals("") && EDIAte.getText().equals("")) {
        query = entityManager.createNamedQuery("Diariafunc.findAll");
        Collection todosDados = query.getResultList();
        list.clear();
        list.addAll(todosDados);
    } else {

        Date ini = null;
        Date fim = null;
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        try {
            ini = formato.parse(EDIDe.getText());
            fim = formato.parse(EDIAte.getText());
        } catch (Exception e) {
            System.out.print(e);
        }
        query = entityManager.createNamedQuery("Diariafunc.findBetweenDataTrabalho");
        query.setParameter("dataIni", ini);
        query.setParameter("dataFim", fim);

        Collection dadosRestposta = query.getResultList();
        list.clear();
        list.addAll(dadosRestposta);
    }

}//GEN-LAST:event_BOTFiltrarActionPerformed

private void RBTNaoTerminadosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_RBTNaoTerminadosItemStateChanged
//atualizaTabelaRBT();
    query = entityManager.createNamedQuery("Diariafunc.findBySituacaodiaria");
    query.setParameter("situacaodiaria", 'S');
    Collection conteudoS = query.getResultList();
    list.clear();
    list.addAll(conteudoS);
}//GEN-LAST:event_RBTNaoTerminadosItemStateChanged

private void RBTTerminadosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_RBTTerminadosItemStateChanged
//atualizaTabelaRBT();
    query = entityManager.createNamedQuery("Diariafunc.findBySituacaodiaria");
    query.setParameter("situacaodiaria", 'N');

    Collection conteudoN = query.getResultList();
    list.clear();
    list.addAll(conteudoN);
}//GEN-LAST:event_RBTTerminadosItemStateChanged

private void RBTTodosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_RBTTodosItemStateChanged
    query = entityManager.createNamedQuery("Diariafunc.findAll");
    Collection todosDados = query.getResultList();
    list.clear();
    list.addAll(todosDados);
}//GEN-LAST:event_RBTTodosItemStateChanged

private void CBXVeiculoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CBXVeiculoFocusLost
}//GEN-LAST:event_CBXVeiculoFocusLost

private void BOTFinalizarTrabalhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTFinalizarTrabalhoActionPerformed
    Date agora = new Date();
    Diariafunc dv = list.get(masterTable.getSelectedRow());
    if (dv.getSituacaoDiaria().equals('S')) {
        if(dv.getSituacaoCorrida().equals('S')){
            JOptionPane.showMessageDialog(null, "Este funcionario possui uma corrida em andamento!", "Funcionario Ocupado",1);
        }else{
        dv.setSituacaoDiaria('N');
        dv.setHoratermino(agora);
        }
    } else {
        JOptionPane.showMessageDialog(null, "Este funcionario ja não esta mais ativo!", "Funcionario Inativo", 1);
    }
}//GEN-LAST:event_BOTFinalizarTrabalhoActionPerformed

private void BOTImprimir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTImprimir2ActionPerformed
query = entityManager.createNamedQuery("Diariafunc.findAll");
        List<sys.taxi.com.br.bean.Diariafunc> diaria = query.getResultList();
    
    
PrinterMatrix printer=new PrinterMatrix();
printer.setOutSize( diaria.size() + 6, 70 );
printer.printCharAtCol( 1, 1, 70, "=" );
printer.printTextLinCol( 2, 1, printer.centralizar(70, "Sistema VGCT - Relatorio de Lucro de caixa"));//42

printer.printCharAtCol( 3, 1, 70, "*" );
printer.printTextLinCol( 4, 1, "Nome Funcionario" );
printer.printTextLinCol( 4, 30, "| Nome Veiculo" );
printer.printTextLinCol( 4, 48, "| Data Trabalho" );
printer.printCharAtCol( 5, 1, 70, "-" );    

int linha = 6;
for (sys.taxi.com.br.bean.Diariafunc d : diaria){
    printer.printTextLinCol( linha, 1, d.getCodfunc().getNomefunc());
    printer.printTextLinCol( linha, 30,"| "+ d.getCodveiculo().getNomevei());
    printer.printTextLinCol( linha, 48,"| "+ d.getDatatrabalho());
    printer.printCharAtCol(linha+1, 1, 60, "-");
    
    linha++;
    
}


printer.printCharAtCol( linha, 1, 70, "=" );    
printer.toImageFile("src/sys/taxi/com/all/Images/Imprensao/diaria.jpg");
    
    
            //areaRelatorio.setText(carregaArquivo("veiculos.txt"));
            //areaRelatorio.moveCaretPosition(0);
            //jLabel1.setIcon(new ImageIcon("src/veiculos.jpg"));
            folha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/Imprensao/diaria.jpg")));
        
    PainelImpresao.setSelectedIndex(1);
}//GEN-LAST:event_BOTImprimir2ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
tabelaDiaria.setSelectedIndex(0);
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
tabelaDiaria.setSelectedIndex(0);
PainelImpresao.setSelectedIndex(0);
}//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTCancela;
    private javax.swing.JButton BOTCancelar;
    private javax.swing.JButton BOTControleVistoria;
    private javax.swing.JButton BOTEditar;
    private javax.swing.JButton BOTFiltrar;
    private javax.swing.JButton BOTFinalizarTrabalho;
    private javax.swing.JButton BOTImprimir2;
    private javax.swing.JButton BOTRelatorio;
    private javax.swing.JButton BOTSalvar;
    private javax.swing.JButton BOTSalvar1;
    private javax.swing.JButton BOTSalvarVistoria;
    private javax.swing.JPanel Botoes;
    private javax.swing.JComboBox CBXFuncionario;
    private javax.swing.JComboBox CBXLocal;
    private javax.swing.JComboBox CBXSituacao;
    private javax.swing.JComboBox CBXVeiculo;
    private javax.swing.JPanel CadastroDiaria;
    private javax.swing.JPanel CadastroVistoria;
    private javax.swing.JPanel Consulta;
    private javax.swing.JPanel ControleFerramenta;
    private javax.swing.JPanel DadosBotaoVistoria;
    private javax.swing.JPanel DadosVistoria;
    private javax.swing.JTextField EDIAte;
    private javax.swing.JFormattedTextField EDIDataTrabalho;
    private javax.swing.JTextField EDIDe;
    private javax.swing.JTextField EDIDescricao;
    private javax.swing.JTextField EDIExtras;
    private javax.swing.JFormattedTextField EDIHoraInicio;
    private javax.swing.JFormattedTextField EDIHoraTermino;
    private javax.swing.JTextField EDILocalVistoria;
    private javax.swing.JTextField EDIObservacao;
    private javax.swing.JTextField EDIPesquisar;
    private javax.swing.JToolBar FerramentaBotoes;
    private javax.swing.JPanel Impressao;
    private javax.swing.JTabbedPane PainelImpresao;
    private javax.swing.JPanel Pesquisa;
    private javax.swing.JRadioButton RBTNaoTerminados;
    private javax.swing.JRadioButton RBTTerminados;
    private javax.swing.JRadioButton RBTTodos;
    private javax.swing.JLabel TEXDescricao;
    private javax.swing.JLabel TEXEditar;
    private javax.swing.JLabel TEXExtras;
    private javax.swing.JLabel TEXLocalVistoria;
    private javax.swing.JLabel TEXObservacao;
    private javax.swing.JPanel Vistoria;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton deleteDetailButton;
    private javax.swing.JScrollPane detailScrollPane;
    private javax.swing.JTable detailTable;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.ButtonGroup exibicaoTerminados;
    private javax.swing.JLabel folha;
    private java.util.List<sys.taxi.com.br.bean.Funcionario> funcionarioList;
    private javax.persistence.Query funcionarioQuery;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private java.util.List<sys.taxi.com.br.bean.Funcionario> lacoFunc;
    private java.util.List<sys.taxi.com.br.bean.Veiculo> lacoVeiculo;
    private java.util.List<sys.taxi.com.br.bean.Diariafunc> list;
    private javax.swing.JScrollPane masterScrollPane;
    private javax.swing.JTable masterTable;
    private javax.swing.JButton newButton;
    private javax.swing.JButton newDetailButton;
    private javax.persistence.Query query;
    private javax.swing.JButton refreshButton;
    private sys.taxi.com.all.util.RowSorterToStringConverter rowSorterToStringConverter1;
    private javax.swing.JButton saveButton;
    private javax.swing.JTabbedPane tabelaDiaria;
    private sys.taxi.com.all.renderer.UnidadeListCellRendererFuncionario unidadeListCellRendererFuncionario1;
    private sys.taxi.com.all.renderer.UnidadeListCellRendererVeiculo unidadeListCellRendererVeiculo1;
    private java.util.List<sys.taxi.com.br.bean.Veiculo> veiculoList;
    private javax.persistence.Query veiculoQuery;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    public static void main(final String[] args, final String da) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiariaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiariaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiariaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiariaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {

            public void run() {
                JFrame frame = new JFrame();
                frame.setContentPane(new DiariaView(da));
                frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                frame.pack();
                frame.setVisible(true);
                frame.setTitle(args[0]);
            }
        });
    }

    /*private void limpandoOsChatos() {
        CBXSituacao.setSelectedItem(" ");
        EDIDataTrabalho.setText("");
        EDIHoraInicio.setText("");
        EDIHoraTermino.setText("");
    } */

    private void voltandoDadosTabelaInicial() {
    exibicaoTerminados.clearSelection();
    EDIDe.setText("");
    EDIAte.setText("");
    query = entityManager.createNamedQuery("Diariafunc.findAll");
    Collection todasDiarias = query.getResultList();
    list.clear();
    list.addAll(todasDiarias);
    }

    private void atualizaDiariaInsere() {

        //capturando todas as diarias que estiverem ativas
        query = entityManager.createNamedQuery("Diariafunc.findBySituacaodiaria");
        query.setParameter("situacaodiaria", 'S');
        List<Diariafunc> atualizado = query.getResultList();
        //capturando todos os funcionarios
        funcionarioQuery = entityManager.createNamedQuery("Funcionario.findAll");
        List<sys.taxi.com.br.bean.Funcionario> funcionario = funcionarioQuery.getResultList();
        funcionarioList.clear();
        funcionarioList.addAll(funcionario);
        
        
        
        //funcionarioList.clear();
        int cont = -1;
        int cont2 = -1;

        //criando um laço que utilizara as diarias ativas para capturar o codigo do funcionario
        for (sys.taxi.com.br.bean.Diariafunc diaria : atualizado) {

            cont = -1;
            cont2 = -1;
            //criando um laço que retire da list os funcionarios que estao ativos por meio deste filtro
            for (Funcionario funcionario1 : funcionario) {
                //extraindo o codigo do funcionario selecionado
                String dadosCampo = "" + diaria.getCodfunc();
                dadosCampo = dadosCampo.substring((dadosCampo.indexOf("=") + 1), (dadosCampo.indexOf("]") - 1));
                cont = cont + 1;
                //achando o funcionario que esta ativo de dentro da list, para retira-lo
                if (funcionario1.getCodfunc() == Integer.parseInt(dadosCampo)) {
                    if (funcionarioList.size() > cont) {
                        funcionarioList.remove(cont);
                    } else {
                        cont2 = -1;
                        lacoFunc.clear();
                        lacoFunc.addAll(funcionarioList);
                        //laço 2 que faz o segundo filtro para achar os funcionarios ativos e retira-los
                        for (Funcionario funcionario2 : lacoFunc) {
                            cont2 = cont2 + 1;
                            if (funcionario2.getCodfunc() == Integer.parseInt(dadosCampo)) {
                                funcionarioList.remove(cont2);
                            }
                        }
                    }


                }
            }

        }



        //funcionarioList.clear();
        //funcionarioList.addAll(atualizado);


        veiculoQuery = entityManager.createNamedQuery("Veiculo.findAll");
        List<sys.taxi.com.br.bean.Veiculo> atualizado2 = veiculoQuery.getResultList();
        veiculoList.clear();
        veiculoList.addAll(atualizado2);
        
        for (sys.taxi.com.br.bean.Diariafunc diaria : atualizado) {

            cont = -1;
            cont2 = -1;
            //criando um laço que retire da list os veiculos que estao ativos por meio deste filtro
            for (sys.taxi.com.br.bean.Veiculo veiculo : atualizado2) {
                //extraindo o codigo do veiculo selecionado
                String dadosCampo = "" + diaria.getCodveiculo();
                dadosCampo = dadosCampo.substring((dadosCampo.indexOf("=") + 1), (dadosCampo.indexOf("]") - 1));
                cont = cont + 1;
                //achando o funcionario que esta ativo de dentro da list, para retira-lo
                if (veiculo.getCodveiculo() == Integer.parseInt(dadosCampo)) {
                    if (veiculoList.size() > cont) {
                        veiculoList.remove(cont);
                    } else {
                        cont2 = -1;
                        lacoVeiculo.clear();
                        lacoVeiculo.addAll(veiculoList);
                        //laço 2 que faz o segundo filtro para achar os funcionarios ativos e retira-los
                        for (sys.taxi.com.br.bean.Veiculo veiculo2 : lacoVeiculo) {
                            cont2 = cont2 + 1;
                            if (veiculo2.getCodveiculo() == Integer.parseInt(dadosCampo)) {
                                veiculoList.remove(cont2);
                            }
                        }
                    }


                }
            }

        }
        
    }
    
    private void botaoOculto(JButton botao){
            botao.setBorderPainted(false); 
            botao.setContentAreaFilled(false); 
            botao.setFocusPainted(false);             
}
    
}

