/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FuncionarioView.java
 *
 * Created on 12/01/2013, 18:55:20
 */
package sys.taxi.com.br.view;

import br.com.adilson.util.PrinterMatrix;
import java.sql.Connection;
import java.awt.EventQueue;
import java.beans.Beans;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.persistence.RollbackException;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import sys.taxi.com.all.util.Data;
import sys.taxi.com.all.util.FormatarCampos;
import sys.taxi.com.br.util.ConexaoSQL;

/**
 *
 * @author VGCT
 */
public class FuncionarioView extends JPanel {
    
    public FuncionarioView(String fc) {
        initComponents();
        if (!Beans.isDesignTime()) {
            entityManager.getTransaction().begin();
        }
        botaoOculto(saveButton);
        botaoOculto(BOTCancelar);
        botaoOculto(BOTRelatorio);
        seriectpsfuncField.setVisible(false);
        letracnhfuncField.setVisible(false);
        if ("C".equals(fc)){
            jPanel4.setVisible(false);
        }else{
            jPanel4.setVisible(true);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("taxiPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT f FROM Funcionario f");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        rowSorterToStringConverter1 = new sys.taxi.com.all.util.RowSorterToStringConverter();
        PainelFuncionario = new javax.swing.JTabbedPane();
        Consulta = new javax.swing.JPanel();
        Pesquisar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        EDIPesquisa = new javax.swing.JTextField();
        masterScrollPane = new javax.swing.JScrollPane();
        masterTable = new javax.swing.JTable();
        FerramentaBotoes = new javax.swing.JToolBar();
        jPanel4 = new javax.swing.JPanel();
        refreshButton = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        BOTSalvar = new javax.swing.JButton();
        BOTEditar = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        BOTRelatorio = new javax.swing.JButton();
        BOTPermissoes = new javax.swing.JButton();
        Cadastro = new javax.swing.JPanel();
        InformacaoFunc = new javax.swing.JPanel();
        nomefuncLabel = new javax.swing.JLabel();
        cpffuncLabel = new javax.swing.JLabel();
        emailfuncLabel = new javax.swing.JLabel();
        celularfuncLabel = new javax.swing.JLabel();
        telefonefuncLabel = new javax.swing.JLabel();
        cnhfuncLabel = new javax.swing.JLabel();
        ctpsfuncLabel = new javax.swing.JLabel();
        nomefuncField = new javax.swing.JTextField();
        cnhfuncField = new javax.swing.JTextField();
        letracnhfuncField = new javax.swing.JTextField();
        emailfuncField = new javax.swing.JTextField();
        ctpsfuncField = new javax.swing.JTextField();
        seriectpsfuncField = new javax.swing.JTextField();
        datanasfuncLabel = new javax.swing.JLabel();
        EDIDataNascimentoFunc = new javax.swing.JFormattedTextField();
        cpffuncField = new javax.swing.JFormattedTextField();
        telefonefuncField = new javax.swing.JFormattedTextField();
        celularfuncField = new javax.swing.JFormattedTextField();
        EnderecoFunc = new javax.swing.JPanel();
        cidadefuncField = new javax.swing.JTextField();
        bairrofuncField = new javax.swing.JTextField();
        enderecofuncField = new javax.swing.JTextField();
        complementofuncField = new javax.swing.JTextField();
        cepfuncLabel = new javax.swing.JLabel();
        uffuncLabel = new javax.swing.JLabel();
        cidadefuncLabel = new javax.swing.JLabel();
        bairrofuncLabel = new javax.swing.JLabel();
        enderecofuncLabel = new javax.swing.JLabel();
        complementofuncLabel = new javax.swing.JLabel();
        numerocasafuncLabel = new javax.swing.JLabel();
        numerocasafuncField = new javax.swing.JTextField();
        CBXUfFunc = new javax.swing.JComboBox();
        EDICep = new javax.swing.JFormattedTextField();
        DadosFunc = new javax.swing.JPanel();
        dataadmicaofuncLabel = new javax.swing.JLabel();
        casadoLabel = new javax.swing.JLabel();
        filhosLabel = new javax.swing.JLabel();
        numerofilhosfuncLabel = new javax.swing.JLabel();
        numerofilhosfuncField = new javax.swing.JTextField();
        EDIDataCadastroFunc = new javax.swing.JFormattedTextField();
        CBXCasado = new javax.swing.JComboBox();
        CBXFilhos = new javax.swing.JComboBox();
        BOTDataAtual = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        BOTCancelar = new javax.swing.JButton();
        Impressao = new javax.swing.JPanel();
        PainelImpresao = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        BOTImprimir2 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        folha = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        PANRelatorio = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        RRelatorio = new javax.swing.JPanel();

        FormListener formListener = new FormListener();

        rowSorterToStringConverter1.setTable(masterTable);

        PainelFuncionario.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        PainelFuncionario.setToolTipText("");

        Pesquisar.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setText("Pesquisar :");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${rowSorter}"), EDIPesquisa, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setConverter(rowSorterToStringConverter1);
        bindingGroup.addBinding(binding);

        EDIPesquisa.addActionListener(formListener);

        javax.swing.GroupLayout PesquisarLayout = new javax.swing.GroupLayout(Pesquisar);
        Pesquisar.setLayout(PesquisarLayout);
        PesquisarLayout.setHorizontalGroup(
            PesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PesquisarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(75, 75, 75)
                .addComponent(EDIPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PesquisarLayout.setVerticalGroup(
            PesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PesquisarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EDIPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        masterTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        masterTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        masterTable.setMaximumSize(new java.awt.Dimension(345, 0));

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list, masterTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nomefunc}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cpffunc}"));
        columnBinding.setColumnName("CPF");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${datanasfunc}"));
        columnBinding.setColumnName("Data Nascimento");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dataadmicaofunc}"));
        columnBinding.setColumnName("Data Admição");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${telefonefunc}"));
        columnBinding.setColumnName("Telefone");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${celularfunc}"));
        columnBinding.setColumnName("Celular");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${emailfunc}"));
        columnBinding.setColumnName("Email");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cnhfunc}"));
        columnBinding.setColumnName("CNH");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${letracnhfunc}"));
        columnBinding.setColumnName("Letra CNH");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cepfunc}"));
        columnBinding.setColumnName("CEP");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${uffunc}"));
        columnBinding.setColumnName("UF");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cidadefunc}"));
        columnBinding.setColumnName("Cidade");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${bairrofunc}"));
        columnBinding.setColumnName("Bairro");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${enderecofunc}"));
        columnBinding.setColumnName("Endereço");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${numerocasafunc}"));
        columnBinding.setColumnName("Número Casa");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${complementofunc}"));
        columnBinding.setColumnName("Complemento");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${casado}"));
        columnBinding.setColumnName("Casado");
        columnBinding.setColumnClass(Character.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${filhos}"));
        columnBinding.setColumnName("Filhos");
        columnBinding.setColumnClass(Character.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${numerofilhosfunc}"));
        columnBinding.setColumnName("Número Filhos");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${ctpsfunc}"));
        columnBinding.setColumnName("CTPS");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${seriectpsfunc}"));
        columnBinding.setColumnName("Serie CTPS");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${foto}"));
        columnBinding.setColumnName("Foto");
        columnBinding.setColumnClass(Character.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codfunc}"));
        columnBinding.setColumnName("Codfunc");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        masterScrollPane.setViewportView(masterTable);
        masterTable.getColumnModel().getColumn(0).setPreferredWidth(230);
        masterTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        masterTable.getColumnModel().getColumn(2).setResizable(false);
        masterTable.getColumnModel().getColumn(2).setPreferredWidth(110);
        masterTable.getColumnModel().getColumn(3).setPreferredWidth(100);
        masterTable.getColumnModel().getColumn(4).setPreferredWidth(100);
        masterTable.getColumnModel().getColumn(5).setPreferredWidth(100);
        masterTable.getColumnModel().getColumn(6).setPreferredWidth(250);
        masterTable.getColumnModel().getColumn(7).setPreferredWidth(100);
        masterTable.getColumnModel().getColumn(8).setPreferredWidth(90);
        masterTable.getColumnModel().getColumn(10).setPreferredWidth(30);
        masterTable.getColumnModel().getColumn(11).setPreferredWidth(100);
        masterTable.getColumnModel().getColumn(12).setPreferredWidth(100);
        masterTable.getColumnModel().getColumn(13).setPreferredWidth(200);
        masterTable.getColumnModel().getColumn(14).setPreferredWidth(100);
        masterTable.getColumnModel().getColumn(15).setPreferredWidth(200);
        masterTable.getColumnModel().getColumn(16).setPreferredWidth(60);
        masterTable.getColumnModel().getColumn(17).setPreferredWidth(50);
        masterTable.getColumnModel().getColumn(18).setPreferredWidth(110);
        masterTable.getColumnModel().getColumn(19).setPreferredWidth(120);

        FerramentaBotoes.setRollover(true);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/ico_atualiza.gif"))); // NOI18N
        refreshButton.setText("Atualizar");
        refreshButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refreshButton.addActionListener(formListener);

        newButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/ico_adicionar.png"))); // NOI18N
        newButton.setText("Incluir");
        newButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newButton.addActionListener(formListener);

        BOTSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/ico_salvar.png"))); // NOI18N
        BOTSalvar.setText("Salvar");
        BOTSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BOTSalvar.addActionListener(formListener);

        BOTEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/ico_editar.png"))); // NOI18N
        BOTEditar.setText("Editar");
        BOTEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), BOTEditar, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        BOTEditar.addActionListener(formListener);

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/ico_excluir.gif"))); // NOI18N
        deleteButton.setText("Excluir");
        deleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), deleteButton, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        deleteButton.addActionListener(formListener);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newButton)
                .addGap(18, 18, 18)
                .addComponent(BOTEditar)
                .addGap(18, 18, 18)
                .addComponent(deleteButton)
                .addGap(18, 18, 18)
                .addComponent(BOTSalvar)
                .addGap(18, 18, 18)
                .addComponent(refreshButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BOTEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BOTSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        FerramentaBotoes.add(jPanel4);

        BOTRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/bot_relatorio 2.png"))); // NOI18N
        BOTRelatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BOTRelatorio.addActionListener(formListener);

        BOTPermissoes.setText("Definir Permições");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), BOTPermissoes, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        BOTPermissoes.addActionListener(formListener);

        javax.swing.GroupLayout ConsultaLayout = new javax.swing.GroupLayout(Consulta);
        Consulta.setLayout(ConsultaLayout);
        ConsultaLayout.setHorizontalGroup(
            ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaLayout.createSequentialGroup()
                .addGroup(ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConsultaLayout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ConsultaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(FerramentaBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BOTRelatorio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BOTPermissoes))
                    .addGroup(ConsultaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(masterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 902, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65))
        );
        ConsultaLayout.setVerticalGroup(
            ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaLayout.createSequentialGroup()
                .addGroup(ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConsultaLayout.createSequentialGroup()
                        .addGroup(ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ConsultaLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(FerramentaBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ConsultaLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(BOTRelatorio)))
                        .addGap(85, 85, 85)
                        .addComponent(Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ConsultaLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(BOTPermissoes)))
                .addGap(18, 18, 18)
                .addComponent(masterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        PainelFuncionario.addTab("Consulta", null, Consulta, "");

        InformacaoFunc.setBackground(new java.awt.Color(204, 204, 255));
        InformacaoFunc.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações"));

        nomefuncLabel.setText("Nome :");

        cpffuncLabel.setText("CPF :");

        emailfuncLabel.setText("Email :");

        celularfuncLabel.setText("Celular :");

        telefonefuncLabel.setText("Telefone :");

        cnhfuncLabel.setText("CNH :");

        ctpsfuncLabel.setText("CTPS :");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.nomefunc}"), nomefuncField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), nomefuncField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.cnhfunc}"), cnhfuncField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), cnhfuncField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        cnhfuncField.addFocusListener(formListener);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.letracnhfunc}"), letracnhfuncField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), letracnhfuncField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.emailfunc}"), emailfuncField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), emailfuncField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.ctpsfunc}"), ctpsfuncField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), ctpsfuncField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        ctpsfuncField.addFocusListener(formListener);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.seriectpsfunc}"), seriectpsfuncField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), seriectpsfuncField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        datanasfuncLabel.setText("Data Nascimento :");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.datanasfunc}"), EDIDataNascimentoFunc, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), EDIDataNascimentoFunc, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        EDIDataNascimentoFunc.addFocusListener(formListener);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.cpffunc}"), cpffuncField, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), cpffuncField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        cpffuncField.addFocusListener(formListener);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.telefonefunc}"), telefonefuncField, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), telefonefuncField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        telefonefuncField.addFocusListener(formListener);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.celularfunc}"), celularfuncField, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), celularfuncField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        celularfuncField.addFocusListener(formListener);

        javax.swing.GroupLayout InformacaoFuncLayout = new javax.swing.GroupLayout(InformacaoFunc);
        InformacaoFunc.setLayout(InformacaoFuncLayout);
        InformacaoFuncLayout.setHorizontalGroup(
            InformacaoFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InformacaoFuncLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InformacaoFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InformacaoFuncLayout.createSequentialGroup()
                        .addComponent(cnhfuncLabel)
                        .addGap(6, 6, 6)
                        .addComponent(cnhfuncField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(letracnhfuncField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(ctpsfuncLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ctpsfuncField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seriectpsfuncField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InformacaoFuncLayout.createSequentialGroup()
                        .addComponent(nomefuncLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomefuncField, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cpffuncLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpffuncField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InformacaoFuncLayout.createSequentialGroup()
                        .addComponent(datanasfuncLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EDIDataNascimentoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(emailfuncLabel)
                        .addGap(22, 22, 22)
                        .addComponent(emailfuncField, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))
                    .addGroup(InformacaoFuncLayout.createSequentialGroup()
                        .addComponent(telefonefuncLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefonefuncField, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                        .addGap(40, 40, 40)
                        .addComponent(celularfuncLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(celularfuncField, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                        .addGap(178, 178, 178)))
                .addContainerGap())
        );
        InformacaoFuncLayout.setVerticalGroup(
            InformacaoFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InformacaoFuncLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InformacaoFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomefuncLabel)
                    .addComponent(nomefuncField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpffuncLabel)
                    .addComponent(cpffuncField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InformacaoFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datanasfuncLabel)
                    .addComponent(emailfuncLabel)
                    .addComponent(emailfuncField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EDIDataNascimentoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InformacaoFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cnhfuncLabel)
                    .addComponent(cnhfuncField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letracnhfuncField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctpsfuncLabel)
                    .addComponent(ctpsfuncField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seriectpsfuncField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InformacaoFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonefuncLabel)
                    .addComponent(telefonefuncField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(celularfuncLabel)
                    .addComponent(celularfuncField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        EnderecoFunc.setBackground(new java.awt.Color(204, 204, 255));
        EnderecoFunc.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.cidadefunc}"), cidadefuncField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), cidadefuncField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.bairrofunc}"), bairrofuncField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), bairrofuncField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.enderecofunc}"), enderecofuncField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), enderecofuncField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.complementofunc}"), complementofuncField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), complementofuncField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        complementofuncField.addActionListener(formListener);

        cepfuncLabel.setText("CEP :");

        uffuncLabel.setText("UF :");

        cidadefuncLabel.setText("Cidade :");

        bairrofuncLabel.setText("Bairro :");

        enderecofuncLabel.setText("Endereço :");

        complementofuncLabel.setText("Complemento :");

        numerocasafuncLabel.setText("Número Casa :");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.numerocasafunc}"), numerocasafuncField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), numerocasafuncField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        CBXUfFunc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.uffunc}"), CBXUfFunc, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), CBXUfFunc, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.cepfunc}"), EDICep, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), EDICep, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        EDICep.addFocusListener(formListener);

        javax.swing.GroupLayout EnderecoFuncLayout = new javax.swing.GroupLayout(EnderecoFunc);
        EnderecoFunc.setLayout(EnderecoFuncLayout);
        EnderecoFuncLayout.setHorizontalGroup(
            EnderecoFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnderecoFuncLayout.createSequentialGroup()
                .addGroup(EnderecoFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EnderecoFuncLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(enderecofuncLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enderecofuncField, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(numerocasafuncLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numerocasafuncField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EnderecoFuncLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(complementofuncLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(complementofuncField, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EnderecoFuncLayout.createSequentialGroup()
                        .addGroup(EnderecoFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(EnderecoFuncLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cidadefuncLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cidadefuncField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(EnderecoFuncLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(cepfuncLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EDICep)))
                        .addGap(45, 45, 45)
                        .addGroup(EnderecoFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EnderecoFuncLayout.createSequentialGroup()
                                .addComponent(uffuncLabel)
                                .addGap(27, 27, 27)
                                .addComponent(CBXUfFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(EnderecoFuncLayout.createSequentialGroup()
                                .addComponent(bairrofuncLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bairrofuncField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        EnderecoFuncLayout.setVerticalGroup(
            EnderecoFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnderecoFuncLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EnderecoFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cepfuncLabel)
                    .addComponent(EDICep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uffuncLabel)
                    .addComponent(CBXUfFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EnderecoFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cidadefuncLabel)
                    .addComponent(cidadefuncField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bairrofuncLabel)
                    .addComponent(bairrofuncField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EnderecoFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enderecofuncLabel)
                    .addComponent(enderecofuncField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numerocasafuncLabel)
                    .addComponent(numerocasafuncField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EnderecoFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(complementofuncLabel)
                    .addComponent(complementofuncField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        DadosFunc.setBackground(new java.awt.Color(204, 204, 255));
        DadosFunc.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));

        dataadmicaofuncLabel.setText("Data Admição :");

        casadoLabel.setText("Casado :");

        filhosLabel.setText("Filhos :");

        numerofilhosfuncLabel.setText("Número Filhos");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.numerofilhosfunc}"), numerofilhosfuncField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, CBXFilhos, org.jdesktop.beansbinding.ELProperty.create("${selectedItem == 'S'}"), numerofilhosfuncField, org.jdesktop.beansbinding.BeanProperty.create("editable"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), numerofilhosfuncField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        EDIDataCadastroFunc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.dataadmicaofunc}"), EDIDataCadastroFunc, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), EDIDataCadastroFunc, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        CBXCasado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "S", "N" }));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.casado}"), CBXCasado, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), CBXCasado, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        CBXFilhos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "S", "N" }));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.filhos}"), CBXFilhos, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), CBXFilhos, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        BOTDataAtual.setToolTipText("Hoje.");
        BOTDataAtual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BOTDataAtual.addActionListener(formListener);

        javax.swing.GroupLayout DadosFuncLayout = new javax.swing.GroupLayout(DadosFunc);
        DadosFunc.setLayout(DadosFuncLayout);
        DadosFuncLayout.setHorizontalGroup(
            DadosFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DadosFuncLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DadosFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DadosFuncLayout.createSequentialGroup()
                        .addGroup(DadosFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filhosLabel)
                            .addGroup(DadosFuncLayout.createSequentialGroup()
                                .addComponent(numerofilhosfuncLabel)
                                .addGap(18, 18, 18)
                                .addComponent(numerofilhosfuncField, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DadosFuncLayout.createSequentialGroup()
                        .addGroup(DadosFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataadmicaofuncLabel)
                            .addComponent(casadoLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DadosFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EDIDataCadastroFunc, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addGroup(DadosFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(CBXCasado, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CBXFilhos, javax.swing.GroupLayout.Alignment.LEADING, 0, 65, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BOTDataAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        DadosFuncLayout.setVerticalGroup(
            DadosFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DadosFuncLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DadosFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BOTDataAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DadosFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dataadmicaofuncLabel)
                        .addComponent(EDIDataCadastroFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(DadosFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(casadoLabel)
                    .addComponent(CBXCasado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DadosFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filhosLabel)
                    .addComponent(CBXFilhos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DadosFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numerofilhosfuncLabel)
                    .addComponent(numerofilhosfuncField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/bot_salvar.png"))); // NOI18N
        saveButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveButton.addActionListener(formListener);

        BOTCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/bot_concela.png"))); // NOI18N
        BOTCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BOTCancelar.addActionListener(formListener);

        javax.swing.GroupLayout CadastroLayout = new javax.swing.GroupLayout(Cadastro);
        Cadastro.setLayout(CadastroLayout);
        CadastroLayout.setHorizontalGroup(
            CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EnderecoFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InformacaoFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastroLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BOTCancelar)
                            .addGroup(CadastroLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(saveButton))))
                    .addGroup(CadastroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DadosFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        CadastroLayout.setVerticalGroup(
            CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastroLayout.createSequentialGroup()
                        .addComponent(DadosFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BOTCancelar))
                    .addGroup(CadastroLayout.createSequentialGroup()
                        .addComponent(InformacaoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(EnderecoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        PainelFuncionario.addTab("Cadastro", Cadastro);

        BOTImprimir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/ico_impressora.png"))); // NOI18N
        BOTImprimir2.setText("Imprimir");
        BOTImprimir2.addActionListener(formListener);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 617, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );

        jButton2.setText("Cancelar Impresão");
        jButton2.addActionListener(formListener);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(286, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(558, Short.MAX_VALUE)
                .addComponent(BOTImprimir2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(186, 186, 186))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BOTImprimir2)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        PainelImpresao.addTab("Propriedades", jPanel10);

        jScrollPane4.setViewportView(folha);

        jButton3.setText("Voltar");
        jButton3.addActionListener(formListener);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(509, Short.MAX_VALUE))
        );

        PainelImpresao.addTab("Imprensao", jPanel12);

        javax.swing.GroupLayout ImpressaoLayout = new javax.swing.GroupLayout(Impressao);
        Impressao.setLayout(ImpressaoLayout);
        ImpressaoLayout.setHorizontalGroup(
            ImpressaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelImpresao, javax.swing.GroupLayout.DEFAULT_SIZE, 977, Short.MAX_VALUE)
        );
        ImpressaoLayout.setVerticalGroup(
            ImpressaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelImpresao, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
        );

        PainelFuncionario.addTab("Impressao", Impressao);

        jButton4.setText("Voltar");
        jButton4.addActionListener(formListener);

        javax.swing.GroupLayout RRelatorioLayout = new javax.swing.GroupLayout(RRelatorio);
        RRelatorio.setLayout(RRelatorioLayout);
        RRelatorioLayout.setHorizontalGroup(
            RRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 915, Short.MAX_VALUE)
        );
        RRelatorioLayout.setVerticalGroup(
            RRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PANRelatorioLayout = new javax.swing.GroupLayout(PANRelatorio);
        PANRelatorio.setLayout(PANRelatorioLayout);
        PANRelatorioLayout.setHorizontalGroup(
            PANRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANRelatorioLayout.createSequentialGroup()
                .addGroup(PANRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PANRelatorioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4))
                    .addComponent(RRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        PANRelatorioLayout.setVerticalGroup(
            PANRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANRelatorioLayout.createSequentialGroup()
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        PainelFuncionario.addTab("tab4", PANRelatorio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 982, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        bindingGroup.bind();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, java.awt.event.FocusListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == EDIPesquisa) {
                FuncionarioView.this.EDIPesquisaActionPerformed(evt);
            }
            else if (evt.getSource() == refreshButton) {
                FuncionarioView.this.refreshButtonActionPerformed(evt);
            }
            else if (evt.getSource() == newButton) {
                FuncionarioView.this.newButtonActionPerformed(evt);
            }
            else if (evt.getSource() == BOTSalvar) {
                FuncionarioView.this.BOTSalvarActionPerformed(evt);
            }
            else if (evt.getSource() == BOTEditar) {
                FuncionarioView.this.BOTEditarActionPerformed(evt);
            }
            else if (evt.getSource() == deleteButton) {
                FuncionarioView.this.deleteButtonActionPerformed(evt);
            }
            else if (evt.getSource() == BOTRelatorio) {
                FuncionarioView.this.BOTRelatorioActionPerformed(evt);
            }
            else if (evt.getSource() == BOTPermissoes) {
                FuncionarioView.this.BOTPermissoesActionPerformed(evt);
            }
            else if (evt.getSource() == complementofuncField) {
                FuncionarioView.this.complementofuncFieldActionPerformed(evt);
            }
            else if (evt.getSource() == BOTDataAtual) {
                FuncionarioView.this.BOTDataAtualActionPerformed(evt);
            }
            else if (evt.getSource() == saveButton) {
                FuncionarioView.this.saveButtonActionPerformed(evt);
            }
            else if (evt.getSource() == BOTCancelar) {
                FuncionarioView.this.BOTCancelarActionPerformed(evt);
            }
            else if (evt.getSource() == BOTImprimir2) {
                FuncionarioView.this.BOTImprimir2ActionPerformed(evt);
            }
            else if (evt.getSource() == jButton2) {
                FuncionarioView.this.jButton2ActionPerformed(evt);
            }
            else if (evt.getSource() == jButton3) {
                FuncionarioView.this.jButton3ActionPerformed(evt);
            }
            else if (evt.getSource() == jButton4) {
                FuncionarioView.this.jButton4ActionPerformed(evt);
            }
        }

        public void focusGained(java.awt.event.FocusEvent evt) {
            if (evt.getSource() == cnhfuncField) {
                FuncionarioView.this.cnhfuncFieldFocusGained(evt);
            }
            else if (evt.getSource() == ctpsfuncField) {
                FuncionarioView.this.ctpsfuncFieldFocusGained(evt);
            }
            else if (evt.getSource() == EDIDataNascimentoFunc) {
                FuncionarioView.this.EDIDataNascimentoFuncFocusGained(evt);
            }
            else if (evt.getSource() == cpffuncField) {
                FuncionarioView.this.cpffuncFieldFocusGained(evt);
            }
            else if (evt.getSource() == telefonefuncField) {
                FuncionarioView.this.telefonefuncFieldFocusGained(evt);
            }
            else if (evt.getSource() == celularfuncField) {
                FuncionarioView.this.celularfuncFieldFocusGained(evt);
            }
            else if (evt.getSource() == EDICep) {
                FuncionarioView.this.EDICepFocusGained(evt);
            }
        }

        public void focusLost(java.awt.event.FocusEvent evt) {
            if (evt.getSource() == cnhfuncField) {
                FuncionarioView.this.cnhfuncFieldFocusLost(evt);
            }
            else if (evt.getSource() == ctpsfuncField) {
                FuncionarioView.this.ctpsfuncFieldFocusLost(evt);
            }
            else if (evt.getSource() == EDIDataNascimentoFunc) {
                FuncionarioView.this.EDIDataNascimentoFuncFocusLost(evt);
            }
            else if (evt.getSource() == cpffuncField) {
                FuncionarioView.this.cpffuncFieldFocusLost(evt);
            }
            else if (evt.getSource() == telefonefuncField) {
                FuncionarioView.this.telefonefuncFieldFocusLost(evt);
            }
            else if (evt.getSource() == celularfuncField) {
                FuncionarioView.this.celularfuncFieldFocusLost(evt);
            }
            else if (evt.getSource() == EDICep) {
                FuncionarioView.this.EDICepFocusLost(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        entityManager.getTransaction().rollback();
        entityManager.getTransaction().begin();
        java.util.Collection data = query.getResultList();
        for (Object entity : data) {
            entityManager.refresh(entity);
        }
        list.clear();
        list.addAll(data);
}//GEN-LAST:event_refreshButtonActionPerformed

private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int[] selected = masterTable.getSelectedRows();
        List<sys.taxi.com.br.bean.Funcionario> toRemove = new ArrayList<sys.taxi.com.br.bean.Funcionario>(selected.length);
        for (int idx = 0; idx < selected.length; idx++) {
            sys.taxi.com.br.bean.Funcionario f = list.get(masterTable.convertRowIndexToModel(selected[idx]));
            toRemove.add(f);
            entityManager.remove(f);
        }
        list.removeAll(toRemove);
}//GEN-LAST:event_deleteButtonActionPerformed

private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
         if (EDIPesquisa.getText() != null)
        {
            EDIPesquisa.setText("");
        }
        PainelFuncionario.setSelectedIndex(1);
        sys.taxi.com.br.bean.Funcionario f = new sys.taxi.com.br.bean.Funcionario();
        entityManager.persist(f);
        list.add(f);
        
        int row = list.size() - 1;
        //int row = masterTable.getComponentCount() -1;
        
        masterTable.setRowSelectionInterval(row, row);
        
        masterTable.scrollRectToVisible(masterTable.getCellRect(row, 0, true));
        
}//GEN-LAST:event_newButtonActionPerformed

FormatarCampos formatarText =  new FormatarCampos();

private void cpffuncFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpffuncFieldFocusGained
    conteudoCpf = cpffuncField.getText();
    formatarText.gainedMascara(cpffuncField, "###.###.###-##");
    cpffuncField.setText(conteudoCpf);
}//GEN-LAST:event_cpffuncFieldFocusGained
String conteudoCpf;
private void cpffuncFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpffuncFieldFocusLost
formatarText.lostMascara(cpffuncField, "   .   .   -  ", "###########");
conteudoCpf = cpffuncField.getText();
}//GEN-LAST:event_cpffuncFieldFocusLost

private void BOTDataAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTDataAtualActionPerformed
    Data setadata = new Data();
    setadata.setaDataAtual(EDIDataCadastroFunc);
}//GEN-LAST:event_BOTDataAtualActionPerformed

private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            entityManager.getTransaction().commit();
            entityManager.getTransaction().begin();
        } catch (RollbackException rex) {
            rex.printStackTrace();
            entityManager.getTransaction().begin();
            List<sys.taxi.com.br.bean.Funcionario> merged = new ArrayList<sys.taxi.com.br.bean.Funcionario>(list.size());
            for (sys.taxi.com.br.bean.Funcionario f : list) {
                merged.add(entityManager.merge(f));
            }
            list.clear();
            list.addAll(merged);
            JOptionPane.showMessageDialog(null, "Não é possivel excluir o registro, certifique que este funcionario nao esta sendo utilizado em outra tabela !");
            refreshButton.doClick();
        }finally{
            PainelFuncionario.setSelectedIndex(0);
        }
}//GEN-LAST:event_saveButtonActionPerformed

private void BOTCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTCancelarActionPerformed
 if (EDIPesquisa.getText() != null)
        {
            EDIPesquisa.setText("");
        }
refreshButton.doClick();
PainelFuncionario.setSelectedIndex(0);
}//GEN-LAST:event_BOTCancelarActionPerformed

private void EDIPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDIPesquisaActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_EDIPesquisaActionPerformed

private void telefonefuncFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonefuncFieldFocusGained
    conteudoTelefone = telefonefuncField.getText();
    formatarText.gainedMascara(telefonefuncField, "(##)####-####");
    telefonefuncField.setText(conteudoTelefone);
}//GEN-LAST:event_telefonefuncFieldFocusGained
String conteudoTelefone;
private void telefonefuncFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonefuncFieldFocusLost
formatarText.lostMascara(telefonefuncField, "(  )    -    ","##########");
conteudoTelefone = telefonefuncField.getText();
}//GEN-LAST:event_telefonefuncFieldFocusLost

private void celularfuncFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_celularfuncFieldFocusGained
    conteudoCelular = celularfuncField.getText();
    formatarText.gainedMascara(celularfuncField, "(##)####-####");
celularfuncField.setText(conteudoCelular);
}//GEN-LAST:event_celularfuncFieldFocusGained
String conteudoCelular;
private void celularfuncFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_celularfuncFieldFocusLost
    formatarText.lostMascara(celularfuncField, "(  )    -    ","##########");
    conteudoCelular = celularfuncField.getText();
}//GEN-LAST:event_celularfuncFieldFocusLost

private void EDICepFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EDICepFocusGained
    conteudoCep = EDICep.getText();
    formatarText.gainedMascara(EDICep, "##.###-###");
    EDICep.setText(conteudoCep);
}//GEN-LAST:event_EDICepFocusGained
String conteudoCep = "1";
private void EDICepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EDICepFocusLost
formatarText.lostMascara(EDICep, "  .   -   ", "########");
conteudoCep = EDICep.getText();
}//GEN-LAST:event_EDICepFocusLost

private void BOTSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTSalvarActionPerformed
saveButton.doClick();
}//GEN-LAST:event_BOTSalvarActionPerformed

private void BOTEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTEditarActionPerformed
    sys.taxi.com.br.bean.Funcionario func = list.get(masterTable.getSelectedRow());
    CBXFilhos.setSelectedItem(""+func.getFilhos());
    CBXCasado.setSelectedItem(""+func.getCasado());
    PainelFuncionario.setSelectedIndex(1);
}//GEN-LAST:event_BOTEditarActionPerformed

private void cnhfuncFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnhfuncFieldFocusGained

}//GEN-LAST:event_cnhfuncFieldFocusGained

private void cnhfuncFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnhfuncFieldFocusLost
// TODO add your handling code here:
}//GEN-LAST:event_cnhfuncFieldFocusLost

private void ctpsfuncFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ctpsfuncFieldFocusGained
// TODO add your handling code here:
}//GEN-LAST:event_ctpsfuncFieldFocusGained

private void ctpsfuncFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ctpsfuncFieldFocusLost
// TODO add your handling code here:
}//GEN-LAST:event_ctpsfuncFieldFocusLost

private void EDIDataNascimentoFuncFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EDIDataNascimentoFuncFocusGained
    
}//GEN-LAST:event_EDIDataNascimentoFuncFocusGained

private void EDIDataNascimentoFuncFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EDIDataNascimentoFuncFocusLost

}//GEN-LAST:event_EDIDataNascimentoFuncFocusLost

private void complementofuncFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complementofuncFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_complementofuncFieldActionPerformed

private void BOTImprimir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTImprimir2ActionPerformed
query = entityManager.createNamedQuery("Funcionario.findAll");
        List<sys.taxi.com.br.bean.Funcionario> funcionarios = query.getResultList();
    
    
PrinterMatrix printer=new PrinterMatrix();
printer.setOutSize( funcionarios.size() + 6, 70 );
printer.printCharAtCol( 1, 1, 70, "=" );
printer.printTextLinCol( 2, 1, printer.centralizar(70, "Sistema VGCT - Relatorio de Lucro de caixa"));//42

printer.printCharAtCol( 3, 1, 70, "*" );
printer.printTextLinCol( 4, 1, "Nome Funcionario" );
printer.printTextLinCol( 4, 30, "| CPF" );
printer.printTextLinCol( 4, 48, "| Data Nascimento" );
printer.printCharAtCol( 5, 1, 70, "-" );    

int linha = 6;
for (sys.taxi.com.br.bean.Funcionario func : funcionarios){
    printer.printTextLinCol( linha, 1, func.getNomefunc());
    printer.printTextLinCol( linha, 30,"| "+ func.getCpffunc());
    printer.printTextLinCol( linha, 48,"| "+ func.getDatanasfunc());
    printer.printCharAtCol(linha+1, 1, 60, "-");
    
    linha++;
    
}


printer.printCharAtCol( linha, 1, 70, "=" );    
printer.toImageFile("src/sys/taxi/com/all/Images/Imprensao/funcionario.jpg");
    
    
            //areaRelatorio.setText(carregaArquivo("veiculos.txt"));
            //areaRelatorio.moveCaretPosition(0);
            //jLabel1.setIcon(new ImageIcon("src/veiculos.jpg"));
            folha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/Imprensao/funcionario.jpg")));
        
    PainelImpresao.setSelectedIndex(1);
}//GEN-LAST:event_BOTImprimir2ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
PainelFuncionario.setSelectedIndex(0);
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
PainelFuncionario.setSelectedIndex(0);
PainelImpresao.setSelectedIndex(0);
}//GEN-LAST:event_jButton3ActionPerformed

private void BOTRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTRelatorioActionPerformed
//sys.taxi.com.br.util.ConexaoSQL con = new sys.taxi.com.br.util.ConexaoSQL();
    
    try{
    Connection con = new ConexaoSQL().getConnection();
    JasperPrint jp = JasperFillManager.fillReport("./Relatorios/Aulas/RLTFuncionarios.jasper", new HashMap(), con);
    JasperViewer jrv = new JasperViewer(jp);
        if (RRelatorio.getComponentCount() > 0){
    RRelatorio.remove(0);
    RRelatorio.add(jrv.getContentPane());
        }else{
    RRelatorio.add(jrv.getContentPane());
        }
    PainelFuncionario.setSelectedIndex(3);
    //jrv.setVisible(true);
}catch(Exception e ){
    JOptionPane.showMessageDialog(null, "Erro :" +e);
}
}//GEN-LAST:event_BOTRelatorioActionPerformed

private void BOTPermissoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTPermissoesActionPerformed
sys.taxi.com.br.bean.Funcionario fn = list.get(masterTable.getSelectedRow());
NivelAcessoView na = new NivelAcessoView(null, true);
//na.recebeFunc(list.get(masterTable.getSelectedRow()), fn.getCodfunc());
na.setLocationRelativeTo(null);
na.setDadoAcesso(list.get(masterTable.getSelectedRow()));
na.setVisible(true);
saveButton.doClick();
}//GEN-LAST:event_BOTPermissoesActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
PainelFuncionario.setSelectedIndex(0);
}//GEN-LAST:event_jButton4ActionPerformed

    
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTCancelar;
    private javax.swing.JButton BOTDataAtual;
    private javax.swing.JButton BOTEditar;
    private javax.swing.JButton BOTImprimir2;
    private javax.swing.JButton BOTPermissoes;
    private javax.swing.JButton BOTRelatorio;
    private javax.swing.JButton BOTSalvar;
    private javax.swing.JComboBox CBXCasado;
    private javax.swing.JComboBox CBXFilhos;
    private javax.swing.JComboBox CBXUfFunc;
    private javax.swing.JPanel Cadastro;
    private javax.swing.JPanel Consulta;
    private javax.swing.JPanel DadosFunc;
    private javax.swing.JFormattedTextField EDICep;
    private javax.swing.JFormattedTextField EDIDataCadastroFunc;
    private javax.swing.JFormattedTextField EDIDataNascimentoFunc;
    private javax.swing.JTextField EDIPesquisa;
    private javax.swing.JPanel EnderecoFunc;
    private javax.swing.JToolBar FerramentaBotoes;
    private javax.swing.JPanel Impressao;
    private javax.swing.JPanel InformacaoFunc;
    private javax.swing.JPanel PANRelatorio;
    private javax.swing.JTabbedPane PainelFuncionario;
    private javax.swing.JTabbedPane PainelImpresao;
    private javax.swing.JPanel Pesquisar;
    private javax.swing.JPanel RRelatorio;
    private javax.swing.JTextField bairrofuncField;
    private javax.swing.JLabel bairrofuncLabel;
    private javax.swing.JLabel casadoLabel;
    private javax.swing.JFormattedTextField celularfuncField;
    private javax.swing.JLabel celularfuncLabel;
    private javax.swing.JLabel cepfuncLabel;
    private javax.swing.JTextField cidadefuncField;
    private javax.swing.JLabel cidadefuncLabel;
    private javax.swing.JTextField cnhfuncField;
    private javax.swing.JLabel cnhfuncLabel;
    private javax.swing.JTextField complementofuncField;
    private javax.swing.JLabel complementofuncLabel;
    private javax.swing.JFormattedTextField cpffuncField;
    private javax.swing.JLabel cpffuncLabel;
    private javax.swing.JTextField ctpsfuncField;
    private javax.swing.JLabel ctpsfuncLabel;
    private javax.swing.JLabel dataadmicaofuncLabel;
    private javax.swing.JLabel datanasfuncLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField emailfuncField;
    private javax.swing.JLabel emailfuncLabel;
    private javax.swing.JTextField enderecofuncField;
    private javax.swing.JLabel enderecofuncLabel;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel filhosLabel;
    private javax.swing.JLabel folha;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField letracnhfuncField;
    private java.util.List<sys.taxi.com.br.bean.Funcionario> list;
    private javax.swing.JScrollPane masterScrollPane;
    private javax.swing.JTable masterTable;
    private javax.swing.JButton newButton;
    private javax.swing.JTextField nomefuncField;
    private javax.swing.JLabel nomefuncLabel;
    private javax.swing.JTextField numerocasafuncField;
    private javax.swing.JLabel numerocasafuncLabel;
    private javax.swing.JTextField numerofilhosfuncField;
    private javax.swing.JLabel numerofilhosfuncLabel;
    private javax.persistence.Query query;
    private javax.swing.JButton refreshButton;
    private sys.taxi.com.all.util.RowSorterToStringConverter rowSorterToStringConverter1;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField seriectpsfuncField;
    private javax.swing.JFormattedTextField telefonefuncField;
    private javax.swing.JLabel telefonefuncLabel;
    private javax.swing.JLabel uffuncLabel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    public static void main(final String[] args, final String fc) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {

            public void run() {
                JFrame frame = new JFrame();
                frame.setContentPane(new FuncionarioView(fc));
                frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                frame.pack();
                frame.setVisible(true);
                frame.setTitle(args[0]);
            }
        });
    }
 
    private void atualizaFuncionario(){
    
}
    private void botaoOculto(JButton botao){
            botao.setBorderPainted(false); 
            botao.setContentAreaFilled(false); 
            botao.setFocusPainted(false);             
}

    
}
