/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Index.java
 *
 * Created on 27/04/2013, 19:00:35
 */
package sys.taxi.com.br.view;

import java.sql.Connection;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import sys.taxi.com.all.util.Data;
import sys.taxi.com.br.util.ConexaoSQL;
import sys.taxi.com.br.util.SemPermissao;



/**
 *
 * @author VGCT
 */
public class Index extends javax.swing.JFrame {
//String abaAtual;
    /** Creates new form Index */
    public Index() {
        initComponents();
        geraLucrosDiarios();
        geraLucrosMensais();
        funcionarioDoMes();
        
        //this.setUndecorated(false);    
        timerAtualizaDatas.start();
        timerAtualizaDados.start();
        abreTodosForm();
        TEXAbaAtual.setText("Local: Menu");
            this.setResizable(false);
            
            //setExtendedState(MAXIMIZED_BOTH);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timerAtualizaDatas = new org.netbeans.examples.lib.timerbean.Timer();
        timerAtualizaDados = new org.netbeans.examples.lib.timerbean.Timer();
        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("taxiPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Pedidostaxi p");
        Horas = new javax.swing.JPanel();
        TEXMostraHora = new javax.swing.JLabel();
        TEXMostraMinuto = new javax.swing.JLabel();
        TEXIconeHora = new javax.swing.JLabel();
        TEXIconeMinuto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TEXMostraSegundo = new javax.swing.JLabel();
        PANMenu = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        tabelaMenu = new javax.swing.JTabbedPane();
        AbaMenu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        TEXFuncMes = new javax.swing.JLabel();
        Pedidostaxi = new javax.swing.JPanel();
        DiariaFuncionarios = new javax.swing.JPanel();
        Funcionarios = new javax.swing.JPanel();
        Cliente = new javax.swing.JPanel();
        Fornecedor = new javax.swing.JPanel();
        Veiculos = new javax.swing.JPanel();
        Relatorios = new javax.swing.JPanel();
        PANRelatorios = new javax.swing.JPanel();
        BOTVoltar = new javax.swing.JButton();
        PANBotoes = new javax.swing.JPanel();
        BOTMenu = new javax.swing.JButton();
        BOTPedidoTaxi = new javax.swing.JButton();
        BOTDiariaFuncionarios = new javax.swing.JButton();
        BOTFuncionarios = new javax.swing.JButton();
        BOTSair = new javax.swing.JButton();
        BOTVeiculos = new javax.swing.JButton();
        BOTFornecedor = new javax.swing.JButton();
        BOTClientes = new javax.swing.JButton();
        BarraInferior = new javax.swing.JPanel();
        Data = new javax.swing.JPanel();
        TEXMostraAno = new javax.swing.JLabel();
        TEXMostraMes = new javax.swing.JLabel();
        TEXMostraDia = new javax.swing.JLabel();
        TEXFormatoData = new javax.swing.JLabel();
        TEXMostraDiaSemana = new javax.swing.JLabel();
        TEXLucMes = new javax.swing.JLabel();
        TEXLucDia = new javax.swing.JLabel();
        TEXAbaAtual = new javax.swing.JLabel();
        TEXOperadorAtual = new javax.swing.JLabel();
        BMNMenu = new javax.swing.JMenuBar();
        SBMOpcao = new javax.swing.JMenu();
        MENSair = new javax.swing.JMenuItem();
        MENLogof = new javax.swing.JMenuItem();
        SBMCadastros = new javax.swing.JMenu();
        MENClientes = new javax.swing.JMenuItem();
        MENFuncionario = new javax.swing.JMenuItem();
        MENFornecedor = new javax.swing.JMenuItem();
        MENVeiculo = new javax.swing.JMenuItem();
        SBMMovimentos = new javax.swing.JMenu();
        MENDiarias = new javax.swing.JMenuItem();
        MENPedidosDeTaxi = new javax.swing.JMenuItem();
        SBMRelatorios = new javax.swing.JMenu();
        MANRelFuncionarios = new javax.swing.JMenuItem();
        MANRelClientes = new javax.swing.JMenuItem();
        MENRelFornecedores = new javax.swing.JMenuItem();
        MANRelVeiculos = new javax.swing.JMenuItem();

        timerAtualizaDatas.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                atualizandoDatas(evt);
            }
        });

        timerAtualizaDados.setDelay(20000L);
        timerAtualizaDados.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                atualizaDadosGerais(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciamento De Corrida de Taxi");
        setBackground(new java.awt.Color(255, 204, 204));

        Horas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Horas.setLayout(null);

        TEXMostraHora.setFont(new java.awt.Font("Quartz MS", 1, 34));
        TEXMostraHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TEXMostraHora.setText("22");
        TEXMostraHora.setToolTipText("Horas");
        TEXMostraHora.setPreferredSize(new java.awt.Dimension(47, 42));
        Horas.add(TEXMostraHora);
        TEXMostraHora.setBounds(20, 10, 100, 40);

        TEXMostraMinuto.setFont(new java.awt.Font("Quartz MS", 1, 34));
        TEXMostraMinuto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TEXMostraMinuto.setText("30");
        TEXMostraMinuto.setToolTipText("Minutos");
        Horas.add(TEXMostraMinuto);
        TEXMostraMinuto.setBounds(20, 80, 100, 40);

        TEXIconeHora.setBackground(new java.awt.Color(153, 255, 153));
        TEXIconeHora.setVerifyInputWhenFocusTarget(false);
        Horas.add(TEXIconeHora);
        TEXIconeHora.setBounds(10, 10, 120, 0);

        TEXIconeMinuto.setBackground(new java.awt.Color(153, 255, 153));
        TEXIconeMinuto.setVerifyInputWhenFocusTarget(false);
        Horas.add(TEXIconeMinuto);
        TEXIconeMinuto.setBounds(10, 120, 120, 0);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Horas.add(jLabel1);
        jLabel1.setBounds(0, 0, 140, 130);

        TEXMostraSegundo.setFont(new java.awt.Font("Quartz MS", 1, 50));
        TEXMostraSegundo.setForeground(new java.awt.Color(102, 102, 255));
        TEXMostraSegundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TEXMostraSegundo.setText("22");
        TEXMostraSegundo.setToolTipText("Segundos");
        Horas.add(TEXMostraSegundo);
        TEXMostraSegundo.setBounds(0, 0, 140, 130);

        PANMenu.setBackground(new java.awt.Color(204, 255, 204));
        PANMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PANMenu.setLayout(null);

        Menu.setLayout(null);

        tabelaMenu.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/taxi (2).png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/taxi[3].jpg"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel4.setText("Funcionario do Mês");

        TEXFuncMes.setFont(new java.awt.Font("Tekton Pro", 0, 18));
        TEXFuncMes.setText("Victor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TEXFuncMes, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TEXFuncMes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(203, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AbaMenuLayout = new javax.swing.GroupLayout(AbaMenu);
        AbaMenu.setLayout(AbaMenuLayout);
        AbaMenuLayout.setHorizontalGroup(
            AbaMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 915, Short.MAX_VALUE)
            .addGroup(AbaMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AbaMenuLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(AbaMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AbaMenuLayout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel2))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        AbaMenuLayout.setVerticalGroup(
            AbaMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
            .addGroup(AbaMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AbaMenuLayout.createSequentialGroup()
                    .addGap(0, 39, Short.MAX_VALUE)
                    .addGroup(AbaMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AbaMenuLayout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(AbaMenuLayout.createSequentialGroup()
                            .addGap(350, 350, 350)
                            .addComponent(jLabel2)))
                    .addGap(0, 39, Short.MAX_VALUE)))
        );

        tabelaMenu.addTab("Menu", AbaMenu);

        Pedidostaxi.setLayout(new java.awt.CardLayout());
        tabelaMenu.addTab("Pedidos Taxi", Pedidostaxi);

        DiariaFuncionarios.setLayout(new java.awt.CardLayout());
        tabelaMenu.addTab("DiariaFuncionarios", DiariaFuncionarios);

        Funcionarios.setLayout(new java.awt.CardLayout());
        tabelaMenu.addTab("Funcionarios", Funcionarios);

        Cliente.setLayout(new java.awt.CardLayout());
        tabelaMenu.addTab("Cliente", Cliente);

        Fornecedor.setLayout(new java.awt.CardLayout());
        tabelaMenu.addTab("Fornecedor", Fornecedor);

        Veiculos.setLayout(new java.awt.CardLayout());
        tabelaMenu.addTab("Veiculos", Veiculos);

        PANRelatorios.setPreferredSize(new java.awt.Dimension(914, 600));
        PANRelatorios.setRequestFocusEnabled(false);

        javax.swing.GroupLayout PANRelatoriosLayout = new javax.swing.GroupLayout(PANRelatorios);
        PANRelatorios.setLayout(PANRelatoriosLayout);
        PANRelatoriosLayout.setHorizontalGroup(
            PANRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 915, Short.MAX_VALUE)
        );
        PANRelatoriosLayout.setVerticalGroup(
            PANRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
        );

        BOTVoltar.setText("Voltar");

        javax.swing.GroupLayout RelatoriosLayout = new javax.swing.GroupLayout(Relatorios);
        Relatorios.setLayout(RelatoriosLayout);
        RelatoriosLayout.setHorizontalGroup(
            RelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PANRelatorios, javax.swing.GroupLayout.DEFAULT_SIZE, 915, Short.MAX_VALUE)
            .addGroup(RelatoriosLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(BOTVoltar)
                .addContainerGap(790, Short.MAX_VALUE))
        );
        RelatoriosLayout.setVerticalGroup(
            RelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RelatoriosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BOTVoltar)
                .addGap(18, 18, 18)
                .addComponent(PANRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tabelaMenu.addTab("Relatorios", Relatorios);

        Menu.add(tabelaMenu);
        tabelaMenu.setBounds(0, 0, 920, 630);

        PANMenu.add(Menu);
        Menu.setBounds(190, 0, 920, 600);

        PANBotoes.setBackground(new java.awt.Color(204, 204, 255));

        BOTMenu.setText("Menu");
        BOTMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTMenuActionPerformed(evt);
            }
        });

        BOTPedidoTaxi.setText("Pedidos Taxi");
        BOTPedidoTaxi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTPedidoTaxiActionPerformed(evt);
            }
        });

        BOTDiariaFuncionarios.setText("Diaria Funcionarios");
        BOTDiariaFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTDiariaFuncionariosActionPerformed(evt);
            }
        });

        BOTFuncionarios.setText("Funcionarios");
        BOTFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTFuncionariosActionPerformed(evt);
            }
        });

        BOTSair.setText("Sair");
        BOTSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTSairActionPerformed(evt);
            }
        });

        BOTVeiculos.setText("Veiculos");
        BOTVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTVeiculosActionPerformed(evt);
            }
        });

        BOTFornecedor.setText("Fornecedor");
        BOTFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTFornecedorActionPerformed(evt);
            }
        });

        BOTClientes.setText("Cliente");
        BOTClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PANBotoesLayout = new javax.swing.GroupLayout(PANBotoes);
        PANBotoes.setLayout(PANBotoesLayout);
        PANBotoesLayout.setHorizontalGroup(
            PANBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANBotoesLayout.createSequentialGroup()
                .addGroup(PANBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BOTMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(BOTPedidoTaxi, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(BOTDiariaFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(BOTFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addGroup(PANBotoesLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(PANBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BOTClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(BOTFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(BOTVeiculos, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(BOTSair, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))))
                .addContainerGap())
        );
        PANBotoesLayout.setVerticalGroup(
            PANBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANBotoesLayout.createSequentialGroup()
                .addComponent(BOTMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BOTPedidoTaxi, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(BOTDiariaFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BOTFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BOTClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BOTFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(BOTVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BOTSair, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PANMenu.add(PANBotoes);
        PANBotoes.setBounds(0, 0, 192, 623);

        BarraInferior.setBackground(new java.awt.Color(255, 255, 204));
        BarraInferior.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Data.setBackground(new java.awt.Color(204, 255, 204));
        Data.setPreferredSize(new java.awt.Dimension(112, 23));
        Data.setLayout(null);

        TEXMostraAno.setFont(new java.awt.Font("Quartz MS", 1, 15));
        TEXMostraAno.setText("2012");
        TEXMostraAno.setToolTipText("Ano");
        Data.add(TEXMostraAno);
        TEXMostraAno.setBounds(90, -9, 60, 30);

        TEXMostraMes.setFont(new java.awt.Font("Quartz MS", 1, 15));
        TEXMostraMes.setText("12");
        TEXMostraMes.setToolTipText("Mes");
        Data.add(TEXMostraMes);
        TEXMostraMes.setBounds(50, -9, 34, 30);

        TEXMostraDia.setFont(new java.awt.Font("Quartz MS", 1, 15));
        TEXMostraDia.setText("12");
        TEXMostraDia.setToolTipText("Dia");
        Data.add(TEXMostraDia);
        TEXMostraDia.setBounds(10, -9, 34, 30);

        TEXFormatoData.setFont(new java.awt.Font("Quartz MS", 1, 15));
        TEXFormatoData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TEXFormatoData.setText("    /     /      ");
        TEXFormatoData.setToolTipText("Data");
        Data.add(TEXFormatoData);
        TEXFormatoData.setBounds(10, -9, 110, 30);

        TEXMostraDiaSemana.setFont(new java.awt.Font("Tahoma", 1, 14));
        TEXMostraDiaSemana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TEXMostraDiaSemana.setText("Segunda-Feira");
        Data.add(TEXMostraDiaSemana);
        TEXMostraDiaSemana.setBounds(0, 11, 150, 20);

        TEXLucMes.setText("Lucros Mes");

        TEXLucDia.setText("Lucros Dia");

        TEXAbaAtual.setText("Local :");

        TEXOperadorAtual.setText("Local :");

        javax.swing.GroupLayout BarraInferiorLayout = new javax.swing.GroupLayout(BarraInferior);
        BarraInferior.setLayout(BarraInferiorLayout);
        BarraInferiorLayout.setHorizontalGroup(
            BarraInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraInferiorLayout.createSequentialGroup()
                .addGroup(BarraInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TEXAbaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXOperadorAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(154, 154, 154)
                .addComponent(TEXLucDia, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(TEXLucMes, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(Data, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        BarraInferiorLayout.setVerticalGroup(
            BarraInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraInferiorLayout.createSequentialGroup()
                .addGroup(BarraInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Data, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BarraInferiorLayout.createSequentialGroup()
                        .addGroup(BarraInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TEXAbaAtual)
                            .addComponent(TEXLucDia)
                            .addComponent(TEXLucMes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TEXOperadorAtual)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SBMOpcao.setText("Opções");

        MENSair.setText("Sair");
        MENSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENSairActionPerformed(evt);
            }
        });
        SBMOpcao.add(MENSair);

        MENLogof.setText("Trocar Usuario");
        MENLogof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENLogofActionPerformed(evt);
            }
        });
        SBMOpcao.add(MENLogof);

        BMNMenu.add(SBMOpcao);

        SBMCadastros.setText("Cadastros");

        MENClientes.setText("Cliente");
        MENClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENClientesActionPerformed(evt);
            }
        });
        SBMCadastros.add(MENClientes);

        MENFuncionario.setText("Funcionario");
        MENFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENFuncionarioActionPerformed(evt);
            }
        });
        SBMCadastros.add(MENFuncionario);

        MENFornecedor.setText("Fornecedor");
        MENFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENFornecedorActionPerformed(evt);
            }
        });
        SBMCadastros.add(MENFornecedor);

        MENVeiculo.setText("Veiculo");
        MENVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENVeiculoActionPerformed(evt);
            }
        });
        SBMCadastros.add(MENVeiculo);

        BMNMenu.add(SBMCadastros);

        SBMMovimentos.setText("Movimentos");

        MENDiarias.setText("Diarias");
        MENDiarias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENDiariasActionPerformed(evt);
            }
        });
        SBMMovimentos.add(MENDiarias);

        MENPedidosDeTaxi.setText("Pedidos de Taxi");
        MENPedidosDeTaxi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENPedidosDeTaxiActionPerformed(evt);
            }
        });
        SBMMovimentos.add(MENPedidosDeTaxi);

        BMNMenu.add(SBMMovimentos);

        SBMRelatorios.setText("Relatorios");

        MANRelFuncionarios.setText("Funcionarios");
        MANRelFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MANRelFuncionariosActionPerformed(evt);
            }
        });
        SBMRelatorios.add(MANRelFuncionarios);

        MANRelClientes.setText("Clientes");
        MANRelClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MANRelClientesActionPerformed(evt);
            }
        });
        SBMRelatorios.add(MANRelClientes);

        MENRelFornecedores.setText("Fornecedores");
        MENRelFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENRelFornecedoresActionPerformed(evt);
            }
        });
        SBMRelatorios.add(MENRelFornecedores);

        MANRelVeiculos.setText("Veiculos");
        MANRelVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MANRelVeiculosActionPerformed(evt);
            }
        });
        SBMRelatorios.add(MANRelVeiculos);

        BMNMenu.add(SBMRelatorios);

        setJMenuBar(BMNMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PANMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 1115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Horas, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BarraInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(Horas, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PANMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BarraInferior, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void BOTMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTMenuActionPerformed
    /*String args[] = new String[1];
    args[0] = "Menu";
    VeiculosView.main(args, null);
    */
    tabelaMenu.setSelectedIndex(0);
    TEXAbaAtual.setText("Local: Menu");
}//GEN-LAST:event_BOTMenuActionPerformed

private void BOTPedidoTaxiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTPedidoTaxiActionPerformed
    
    tabelaMenu.setSelectedIndex(1);
    TEXAbaAtual.setText("Local: Controle de Pedidos de Taxi");
}//GEN-LAST:event_BOTPedidoTaxiActionPerformed

private void BOTDiariaFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTDiariaFuncionariosActionPerformed
    tabelaMenu.setSelectedIndex(2);
    TEXAbaAtual.setText("Local: Controle de Diarias");
}//GEN-LAST:event_BOTDiariaFuncionariosActionPerformed

private void BOTFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTFuncionariosActionPerformed
    tabelaMenu.setSelectedIndex(3);
    TEXAbaAtual.setText("Local: Cadastro de Funcionarios");
}//GEN-LAST:event_BOTFuncionariosActionPerformed

private void BOTSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTSairActionPerformed
System.exit(0);
}//GEN-LAST:event_BOTSairActionPerformed

private void BOTVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTVeiculosActionPerformed
    tabelaMenu.setSelectedIndex(6);
    TEXAbaAtual.setText("Local: Cadastro de Veiculos");
}//GEN-LAST:event_BOTVeiculosActionPerformed

private void BOTFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTFornecedorActionPerformed
    tabelaMenu.setSelectedIndex(5);
    TEXAbaAtual.setText("Local: Cadastro de Fornecedores");
}//GEN-LAST:event_BOTFornecedorActionPerformed

private void BOTClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTClientesActionPerformed
    tabelaMenu.setSelectedIndex(4);
    TEXAbaAtual.setText("Local: Cadastro de Clientes");
}//GEN-LAST:event_BOTClientesActionPerformed

private void MENClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENClientesActionPerformed
    /*
    String args[] = new String[1];
    args[0] = "Cadastro de Clientes";
    ClienteView.main(args);
    */
    tabelaMenu.setSelectedIndex(4);
    TEXAbaAtual.setText("Local: Cadastro de Clientes");
}//GEN-LAST:event_MENClientesActionPerformed

private void MENSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENSairActionPerformed
System.exit(0);
}//GEN-LAST:event_MENSairActionPerformed

private void MENFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENFuncionarioActionPerformed
tabelaMenu.setSelectedIndex(3);
TEXAbaAtual.setText("Local: Cadastro de Funcionarios");
}//GEN-LAST:event_MENFuncionarioActionPerformed

private void MENFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENFornecedorActionPerformed
tabelaMenu.setSelectedIndex(5);
TEXAbaAtual.setText("Local: Cadastro de Fornecedores");
}//GEN-LAST:event_MENFornecedorActionPerformed

private void MENVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENVeiculoActionPerformed
tabelaMenu.setSelectedIndex(6);
TEXAbaAtual.setText("Local: Cadastro de Veiculos");
}//GEN-LAST:event_MENVeiculoActionPerformed

private void MENDiariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENDiariasActionPerformed
tabelaMenu.setSelectedIndex(2);
TEXAbaAtual.setText("Local: Controle de Diarias");
}//GEN-LAST:event_MENDiariasActionPerformed

private void MENPedidosDeTaxiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENPedidosDeTaxiActionPerformed
tabelaMenu.setSelectedIndex(1);
TEXAbaAtual.setText("Local: Controle de Pedidos de Taxi");
}//GEN-LAST:event_MENPedidosDeTaxiActionPerformed

private void atualizandoDatas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizandoDatas
iniciaDatas();
}//GEN-LAST:event_atualizandoDatas

private void atualizaDadosGerais(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizaDadosGerais
geraLucrosDiarios();
geraLucrosMensais();
funcionarioDoMes();
}//GEN-LAST:event_atualizaDadosGerais

private void MANRelFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MANRelFuncionariosActionPerformed

    try{
    Connection con = new ConexaoSQL().getConnection();
    JasperPrint jp = JasperFillManager.fillReport("./Relatorios/Aulas/RLTFuncionarios.jasper", new HashMap(), con);
    JasperViewer jrv = new JasperViewer(jp);
    PANRelatorios.add(jrv.getContentPane());
    tabelaMenu.setSelectedIndex(7);
    //jrv.setVisible(true);
}catch(Exception e ){
    JOptionPane.showMessageDialog(null, "Erro :" +e);
}
}//GEN-LAST:event_MANRelFuncionariosActionPerformed

private void MANRelClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MANRelClientesActionPerformed
    try{
    Connection con = new ConexaoSQL().getConnection();
    JasperPrint jp = JasperFillManager.fillReport("./Relatorios/Aulas/RLTFuncionarios.jasper", new HashMap(), con);
    JasperViewer jrv = new JasperViewer(jp);
    PANRelatorios.add(jrv.getContentPane());
    tabelaMenu.setSelectedIndex(7);
    //jrv.setVisible(true);
}catch(Exception e ){
    JOptionPane.showMessageDialog(null, "Erro :" +e);
}
}//GEN-LAST:event_MANRelClientesActionPerformed

private void MENRelFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENRelFornecedoresActionPerformed
    try{
    Connection con = new ConexaoSQL().getConnection();
    JasperPrint jp = JasperFillManager.fillReport("./Relatorios/Aulas/RLTFuncionarios.jasper", new HashMap(), con);
    JasperViewer jrv = new JasperViewer(jp);
    PANRelatorios.add(jrv.getContentPane());
    tabelaMenu.setSelectedIndex(7);
    //jrv.setVisible(true);
}catch(Exception e ){
    JOptionPane.showMessageDialog(null, "Erro :" +e);
}
}//GEN-LAST:event_MENRelFornecedoresActionPerformed

private void MANRelVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MANRelVeiculosActionPerformed
    try{
    Connection con = new ConexaoSQL().getConnection();
    JasperPrint jp = JasperFillManager.fillReport("./Relatorios/Aulas/RLTFuncionarios.jasper", new HashMap(), con);
    JasperViewer jrv = new JasperViewer(jp);
    PANRelatorios.add(jrv.getContentPane());
    tabelaMenu.setSelectedIndex(7);
    //jrv.setVisible(true);
}catch(Exception e ){
    JOptionPane.showMessageDialog(null, "Erro :" +e);
}
}//GEN-LAST:event_MANRelVeiculosActionPerformed

private void MENLogofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENLogofActionPerformed
        this.dispose();
        Index index = new Index();
        index.show();
}//GEN-LAST:event_MENLogofActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Index menu = new Index();
                menu.setVisible(true);
                menu.setUndecorated(false);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AbaMenu;
    private javax.swing.JMenuBar BMNMenu;
    private javax.swing.JButton BOTClientes;
    private javax.swing.JButton BOTDiariaFuncionarios;
    private javax.swing.JButton BOTFornecedor;
    private javax.swing.JButton BOTFuncionarios;
    private javax.swing.JButton BOTMenu;
    private javax.swing.JButton BOTPedidoTaxi;
    private javax.swing.JButton BOTSair;
    private javax.swing.JButton BOTVeiculos;
    private javax.swing.JButton BOTVoltar;
    private javax.swing.JPanel BarraInferior;
    private javax.swing.JPanel Cliente;
    private javax.swing.JPanel Data;
    private javax.swing.JPanel DiariaFuncionarios;
    private javax.swing.JPanel Fornecedor;
    private javax.swing.JPanel Funcionarios;
    private javax.swing.JPanel Horas;
    private javax.swing.JMenuItem MANRelClientes;
    private javax.swing.JMenuItem MANRelFuncionarios;
    private javax.swing.JMenuItem MANRelVeiculos;
    private javax.swing.JMenuItem MENClientes;
    private javax.swing.JMenuItem MENDiarias;
    private javax.swing.JMenuItem MENFornecedor;
    private javax.swing.JMenuItem MENFuncionario;
    private javax.swing.JMenuItem MENLogof;
    private javax.swing.JMenuItem MENPedidosDeTaxi;
    private javax.swing.JMenuItem MENRelFornecedores;
    private javax.swing.JMenuItem MENSair;
    private javax.swing.JMenuItem MENVeiculo;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel PANBotoes;
    private javax.swing.JPanel PANMenu;
    private javax.swing.JPanel PANRelatorios;
    private javax.swing.JPanel Pedidostaxi;
    private javax.swing.JPanel Relatorios;
    private javax.swing.JMenu SBMCadastros;
    private javax.swing.JMenu SBMMovimentos;
    private javax.swing.JMenu SBMOpcao;
    private javax.swing.JMenu SBMRelatorios;
    private javax.swing.JLabel TEXAbaAtual;
    private javax.swing.JLabel TEXFormatoData;
    private javax.swing.JLabel TEXFuncMes;
    private javax.swing.JLabel TEXIconeHora;
    private javax.swing.JLabel TEXIconeMinuto;
    private javax.swing.JLabel TEXLucDia;
    private javax.swing.JLabel TEXLucMes;
    private javax.swing.JLabel TEXMostraAno;
    private javax.swing.JLabel TEXMostraDia;
    private javax.swing.JLabel TEXMostraDiaSemana;
    private javax.swing.JLabel TEXMostraHora;
    private javax.swing.JLabel TEXMostraMes;
    private javax.swing.JLabel TEXMostraMinuto;
    private javax.swing.JLabel TEXMostraSegundo;
    private javax.swing.JLabel TEXOperadorAtual;
    private javax.swing.JPanel Veiculos;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.persistence.Query query;
    private javax.swing.JTabbedPane tabelaMenu;
    private org.netbeans.examples.lib.timerbean.Timer timerAtualizaDados;
    private org.netbeans.examples.lib.timerbean.Timer timerAtualizaDatas;
    // End of variables declaration//GEN-END:variables

    private void abreTodosForm(){
        sys.taxi.com.br.bean.Funcionario f = new sys.taxi.com.br.bean.Funcionario();
        int cod = 0;
        LoginView lv = new LoginView(null, true);
        //lv.setConfirmaUsuario(f);
        lv.codUsuario(f);
        lv.setLocationRelativeTo(null);
        lv.setVisible(true);
        //SemPermissao semPermissao = new SemPermissao();
        SemPermissao args[] = new SemPermissao[6];
        int form = 0;
        
        if("N".equals(f.getPercli())){
        args[form] = new SemPermissao();
        Cliente.add(args[form]);
        form++;
        }else{
        ClienteView cli = new ClienteView(""+f.getPercli());
        Cliente.add(cli);
        } 
        
        if("N".equals(f.getPerforn())){
        args[form] = new SemPermissao();
        Fornecedor.add(args[form]);    
        form++;
        }else{
        FormView fornecedor = new FormView(""+f.getPerforn());
        Fornecedor.add(fornecedor);
        }
        
        if("N".equals(""+f.getPermicao())){
        args[form] = new SemPermissao();
        Funcionarios.add(args[form]);
        form++;
        }else{
        FuncionarioView funcionarios = new FuncionarioView(""+f.getPermicao());
        Funcionarios.add(funcionarios);
        }
        
        if("N".equals(f.getPervei())){
        args[form] = new SemPermissao();
        Veiculos.add(args[form]);
        form++;
        }else{
        VeiculosView veiculos = new VeiculosView(""+f.getPervei());
        Veiculos.add(veiculos);
        }
        
        if("N".equals(f.getPerped())){
        args[form] = new SemPermissao();
        Pedidostaxi.add(args[form]);
        form++;
        }else{
        PedidoTaxiView pedidostaxi = new PedidoTaxiView(""+f.getPerped());
        Pedidostaxi.add(pedidostaxi);
        }
        
        if("N".equals(f.getPerdia())){
        args[form] = new SemPermissao();
        DiariaFuncionarios.add(args[form]);
        form++;
        }else{
        DiariaView diaria = new DiariaView(""+f.getPerdia());
        DiariaFuncionarios.add(diaria);
        }
        
        TEXOperadorAtual.setText("Operador : "+f.getNomefunc());
    }
    
    private void iniciaDatas(){
        Data data = new Data();
        data.leData();
        TEXMostraAno.setText(""+data.ano);
        TEXMostraDia.setText(""+data.dia);
        TEXMostraMes.setText(""+data.mes);
        TEXMostraDiaSemana.setText(""+data.diaDaSemana);
        data.leHora();
        TEXMostraMinuto.setText(""+data.minuto);
        TEXMostraSegundo.setText(""+data.segundo);
        TEXMostraHora.setText(""+data.hora);
    }
    
    private void geraLucrosDiarios(){
       Date ini = new Date();
      
        Date fim = new Date();
        
        query = entityManager.createNamedQuery("Pedidostaxi.findLucrosData");
        query.setParameter("dataini", ini);
        query.setParameter("datafim", fim);
        double dinheiro = 0;
        //Collection dadosRestposta = query.getResultList();
        List<sys.taxi.com.br.bean.Pedidostaxi> funcDia = query.getResultList();
        
        if (funcDia.isEmpty()){
            TEXLucDia.setText("Não existe lucros diarios !");
        }else{
          for (sys.taxi.com.br.bean.Pedidostaxi pd : funcDia){
            dinheiro = dinheiro + pd.getPrecocorrida();
        }
        TEXLucDia.setText("Lucro Diario é de  : R$"+dinheiro);  
        }               
    }
    
    private void geraLucrosMensais(){
        Data data = new Data();
        data.leData();
        Date ini = new Date();
        Date fim = new Date();
        fim.setMonth(Integer.parseInt(data.mes)-1);
        fim.setDate(30);
        ini.setDate(01);
        ini.setMonth(Integer.parseInt(data.mes)-1);
        System.out.print(ini);
        System.out.print(fim);
        query = entityManager.createNamedQuery("Pedidostaxi.findLucrosData");
        query.setParameter("dataini", ini);
        query.setParameter("datafim", fim);
        
        double dinheiro = 0;
        //Collection dadosRestposta = query.getResultList();
        List<sys.taxi.com.br.bean.Pedidostaxi> funcMes = query.getResultList();
        
        if (funcMes.isEmpty()){
            TEXLucMes.setText("Não existe lucros mensais");
        }else{
            
        for (sys.taxi.com.br.bean.Pedidostaxi pd : funcMes){
            dinheiro = dinheiro + pd.getPrecocorrida();
        }
        TEXLucMes.setText("Lucro Mensal é de  : R$"+dinheiro);
        }
    }
    
    private void funcionarioDoMes(){
        Data data = new Data();
        data.leData();
        Date ini = new Date();
        Date fim = new Date();
        fim.setMonth(Integer.parseInt(data.mes)-1);
        fim.setDate(30);
        ini.setDate(01);
        ini.setMonth(Integer.parseInt(data.mes)-1);
        System.out.print(ini);
        System.out.print(fim);
        query = entityManager.createNamedQuery("Pedidostaxi.findBetweendatapedido");
        query.setParameter("dataini", ini);
        query.setParameter("datafim", fim);
        List<sys.taxi.com.br.bean.Pedidostaxi> funcMes = query.getResultList();
        
        query = entityManager.createNamedQuery("Funcionario.findAll");
        List<sys.taxi.com.br.bean.Funcionario> funcionarios = query.getResultList();
        if (funcMes.isEmpty()){
            TEXFuncMes.setText("Nenhum");
        }else{
            int tamanhoMaior = -1;
            int codFunc = -1;
           
            for (sys.taxi.com.br.bean.Funcionario func : funcionarios){
                //if (pd.getCoddiariafunc().getCodfunc().getCodfunc() == func.getCodfunc()){
                    query = entityManager.createNamedQuery("Pedidostaxi.findByCodfunc");
                    query.setParameter("codfunc", func.getCodfunc());
                    List<sys.taxi.com.br.bean.Funcionario> funcionario = query.getResultList(); 
                    if (funcionario.size() > tamanhoMaior){
                        tamanhoMaior = funcionario.size();
                        codFunc = func.getCodfunc();
                  //  }
                }
            }
        
        
        TEXFuncMes.setText("Funcionario do mes é :");
        }
        
    }
}
