/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NivelAcessoView.java
 *
 * Created on 19/06/2013, 20:15:04
 */
package sys.taxi.com.br.view;

import java.beans.Beans;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import sys.taxi.com.br.bean.Funcionario;

/**
 *
 * @author VGCT
 */
public class NivelAcessoView extends javax.swing.JDialog {

    /** Creates new form NivelAcessoView */
    public NivelAcessoView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        if (!Beans.isDesignTime()) {
            entityManager.getTransaction().begin();
        }
    EDIPerCli.setVisible(false);
    EDIPerDia.setVisible(false);
    EDIPerFor.setVisible(false);
    EDIPerFun.setVisible(false);
    EDIPerPed.setVisible(false);
    EDIPerVei.setVisible(false);
        
    }
    public Funcionario func;
    public int codFunc;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("taxiPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT f FROM Funcionario f");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        BOTConcluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CBXPerPed = new javax.swing.JComboBox();
        CBXPerDia = new javax.swing.JComboBox();
        CBXPerFunc = new javax.swing.JComboBox();
        CBXPerForn = new javax.swing.JComboBox();
        CBXPerCli = new javax.swing.JComboBox();
        CBXPerVei = new javax.swing.JComboBox();
        EDIPerPed = new javax.swing.JTextField();
        EDIPerDia = new javax.swing.JTextField();
        EDIPerFun = new javax.swing.JTextField();
        EDIPerFor = new javax.swing.JTextField();
        EDIPerCli = new javax.swing.JTextField();
        EDIPerVei = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Permissão Funcionario");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        BOTConcluir.setText("Concluir");
        BOTConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTConcluirActionPerformed(evt);
            }
        });

        jLabel1.setText("Permição Pedidos");

        jLabel2.setText("Permição Diaria");

        jLabel3.setText("Permição Funcionario");

        jLabel4.setText("Permição Fornecedor");

        jLabel5.setText("Permição Cliente");

        jLabel6.setText("Permição Veiculo");

        CBXPerPed.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Administrador", "Consulta", "Nenhuma" }));

        CBXPerDia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Administrador", "Consulta", "Nenhuma" }));

        CBXPerFunc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Administrador", "Consulta", "Nenhuma" }));

        CBXPerForn.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Administrador", "Consulta", "Nenhuma" }));

        CBXPerCli.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Administrador", "Consulta", "Nenhuma" }));

        CBXPerVei.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Administrador", "Consulta", "Nenhuma" }));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${dadoAcesso.perped}"), EDIPerPed, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${dadoAcesso.perdia}"), EDIPerDia, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${dadoAcesso.permicao}"), EDIPerFun, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${dadoAcesso.perforn}"), EDIPerFor, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${dadoAcesso.percli}"), EDIPerCli, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        EDIPerCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDIPerCliActionPerformed(evt);
            }
        });

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${dadoAcesso.pervei}"), EDIPerVei, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CBXPerPed, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBXPerDia, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBXPerFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBXPerForn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBXPerCli, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBXPerVei, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EDIPerCli, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EDIPerFor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EDIPerFun, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EDIPerDia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EDIPerPed, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BOTConcluir)
                            .addComponent(EDIPerVei, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CBXPerPed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EDIPerPed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CBXPerDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EDIPerDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CBXPerFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EDIPerFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CBXPerForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EDIPerFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CBXPerCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EDIPerCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CBXPerVei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(EDIPerVei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(BOTConcluir)
                .addGap(51, 51, 51))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void BOTConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTConcluirActionPerformed
//    Funcionario fn = list.get(0);
//    this.func = fn;
//    this.dispose();
    
    /*
    if (CBXPerDia.getSelectedIndex() == 1){
        this.getDadoAcesso().setPerdia("A");
    }else{if(CBXPerDia.getSelectedIndex() == 2){
        this.getDadoAcesso().setPerdia("C");    
    }else{
        this.getDadoAcesso().setPerdia("N");
    }}
    
    if (CBXPerPed.getSelectedIndex() == 1){
        this.getDadoAcesso().setPerped("A");
    }else{if(CBXPerPed.getSelectedIndex() == 2){
        this.getDadoAcesso().setPerped("C");    
    }else{
        this.getDadoAcesso().setPerped("N");
    }}
    
    if (CBXPerFunc.getSelectedIndex() == 1){
        this.getDadoAcesso().setPermicao("A");
    }else{if(CBXPerFunc.getSelectedIndex() == 2){
        this.getDadoAcesso().setPermicao("C");    
    }else{
        this.getDadoAcesso().setPermicao("N");
    }}
    
    if (CBXPerForn.getSelectedIndex() == 1){
        this.getDadoAcesso().setPerforn("A");
    }else{if(CBXPerForn.getSelectedIndex() == 2){
        this.getDadoAcesso().setPerforn("C");    
    }else{
        this.getDadoAcesso().setPerforn("N");
    }}
    
    if (CBXPerCli.getSelectedIndex() == 1){
        this.getDadoAcesso().setPercli("A");
    }else{if(CBXPerCli.getSelectedIndex() == 2){
        this.getDadoAcesso().setPercli("C");    
    }else{
        this.getDadoAcesso().setPercli("N");
    }}
    
    if (CBXPerVei.getSelectedIndex() == 1){
        this.getDadoAcesso().setPervei("A");
    }else{if(CBXPerVei.getSelectedIndex() == 2){
        this.getDadoAcesso().setPervei("C");    
    }else{
        this.getDadoAcesso().setPervei("N");
    }}
    
    */
    
    if (CBXPerDia.getSelectedIndex() == 1){
        EDIPerDia.setText("A");
    }else{if(CBXPerDia.getSelectedIndex() == 2){
        EDIPerDia.setText("C");    
    }else{
        EDIPerDia.setText("N");
    }}
    
    if (CBXPerPed.getSelectedIndex() == 1){
        EDIPerPed.setText("A");
    }else{if(CBXPerPed.getSelectedIndex() == 2){
        EDIPerPed.setText("C");    
    }else{
        EDIPerPed.setText("N");
    }}
    
    if (CBXPerFunc.getSelectedIndex() == 1){
        EDIPerFun.setText("A");
    }else{if(CBXPerFunc.getSelectedIndex() == 2){
        EDIPerFun.setText("C");    
    }else{
        EDIPerFun.setText("N");
    }}
    
    if (CBXPerForn.getSelectedIndex() == 1){
        EDIPerFor.setText("A");
    }else{if(CBXPerForn.getSelectedIndex() == 2){
        EDIPerFor.setText("C");    
    }else{
        EDIPerFor.setText("N");
    }}
    
    if (CBXPerCli.getSelectedIndex() == 1){
        EDIPerCli.setText("A");
    }else{if(CBXPerCli.getSelectedIndex() == 2){
        EDIPerCli.setText("C");    
    }else{
        EDIPerCli.setText("N");
    }}
    
    if (CBXPerVei.getSelectedIndex() == 1){
        EDIPerVei.setText("A");
    }else{if(CBXPerVei.getSelectedIndex() == 2){
        EDIPerVei.setText("C");    
    }else{
        EDIPerVei.setText("N");
    }}
    //this.dadoAcesso.setNomefunc(null);
    
    
    
    setConfirmaAcesso(true);
    setVisible(false);
}//GEN-LAST:event_BOTConcluirActionPerformed

private void EDIPerCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDIPerCliActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_EDIPerCliActionPerformed

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        atualiza(CBXPerCli, EDIPerCli);
        atualiza(CBXPerDia, EDIPerDia);
        atualiza(CBXPerForn, EDIPerFor);
        atualiza(CBXPerFunc, EDIPerFun);
        atualiza(CBXPerPed, EDIPerPed);
        atualiza(CBXPerVei, EDIPerVei);
}//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NivelAcessoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NivelAcessoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NivelAcessoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NivelAcessoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                NivelAcessoView dialog = new NivelAcessoView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTConcluir;
    private javax.swing.JComboBox CBXPerCli;
    private javax.swing.JComboBox CBXPerDia;
    private javax.swing.JComboBox CBXPerForn;
    private javax.swing.JComboBox CBXPerFunc;
    private javax.swing.JComboBox CBXPerPed;
    private javax.swing.JComboBox CBXPerVei;
    private javax.swing.JTextField EDIPerCli;
    private javax.swing.JTextField EDIPerDia;
    private javax.swing.JTextField EDIPerFor;
    private javax.swing.JTextField EDIPerFun;
    private javax.swing.JTextField EDIPerPed;
    private javax.swing.JTextField EDIPerVei;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private java.util.List<sys.taxi.com.br.bean.Funcionario> list;
    private javax.persistence.Query query;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    
    protected boolean ConfirmaAcesso;

    /**
     * Get the value of ConfirmaAcesso
     *
     * @return the value of ConfirmaAcesso
     */
    public boolean isConfirmaAcesso() {
        return ConfirmaAcesso;
    }

    /**
     * Set the value of ConfirmaAcesso
     *
     * @param ConfirmaAcesso new value of ConfirmaAcesso
     */
    public void setConfirmaAcesso(boolean ConfirmaAcesso) {
        this.ConfirmaAcesso = ConfirmaAcesso;
    }

    
    
    
    protected Funcionario dadoAcesso;

    /**
     * Get the value of dadoAcesso
     *
     * @return the value of dadoAcesso
     */
    public Funcionario getDadoAcesso() {
        return dadoAcesso;
    }

    /**
     * Set the value of dadoAcesso
     *
     * @param dadoAcesso new value of dadoAcesso
     */
    public void setDadoAcesso(Funcionario dadoAcesso) {
        Funcionario oldDadoAcesso = this.dadoAcesso;
        this.dadoAcesso = dadoAcesso;
        propertyChangeSupport.firePropertyChange("dadoAcesso",oldDadoAcesso, dadoAcesso);
    }
    private PropertyChangeSupport propertyChangeSupport = new PropertyChangeSupport(this);

    /**
     * Add PropertyChangeListener.
     *
     * @param listener
     */
    public void addPropertyChangeListener(PropertyChangeListener listener) {
        propertyChangeSupport.addPropertyChangeListener(listener);
    }

    /**
     * Remove PropertyChangeListener.
     *
     * @param listener
     */
    public void removePropertyChangeListener(PropertyChangeListener listener) {
        propertyChangeSupport.removePropertyChangeListener(listener);
    }

    
public void recebeFunc(Funcionario func, int codFunc){
    this.func = func;
    //this.codFunc = codFunc;
query = entityManager.createNamedQuery("Funcionario.findByCodfunc");
query.setParameter("codfunc", codFunc);
list.clear();
list.addAll(query.getResultList());
}

public static void atualiza(JComboBox cbx,JTextField edi){
    if ("A".equals(edi.getText())){
      cbx.setSelectedIndex(1);  
    }else{if ("C".equals(edi.getText())){
      cbx.setSelectedIndex(2);    
    }else{if("N".equals(edi.getText())){
        cbx.setSelectedIndex(3);  
    }else{
        cbx.setSelectedIndex(0);
    }}}
}

}
