/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ViewRelatorios.java
 *
 * Created on 10/05/2013, 20:48:35
 */
package sys.taxi.com.all.impresao;

import br.com.adilson.util.PrinterMatrix;
import java.awt.EventQueue;
import java.beans.Beans;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import java.util.List;
import javax.swing.JOptionPane;
import sys.taxi.com.br.view.FormView;

/**
 *
 * @author VGCT
 */
public class ViewRelatorios extends javax.swing.JPanel {

    /** Creates new form ViewRelatorios */
    public ViewRelatorios() {
        initComponents();
        if (!Beans.isDesignTime()) {
            entityManager.getTransaction().begin();
        }
        tabelaDados.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("taxiPU").createEntityManager();
        queryFuncionarios = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT f FROM Funcionario f");
        queryClientes = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Cliente c");
        queryFornecedores = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT f FROM Fornecedor f");
        queryVeiculos = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT v FROM Veiculo v");
        GRBTipoRelatorio = new javax.swing.ButtonGroup();
        PainelImpressao = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        CBXTipoImpresao = new javax.swing.JComboBox();
        BOTImprimir = new javax.swing.JButton();
        tabelaDados = new javax.swing.JTabbedPane();
        tipoFunc = new javax.swing.JPanel();
        tipoCli = new javax.swing.JPanel();
        tipoForn = new javax.swing.JPanel();
        tipoVei = new javax.swing.JPanel();
        PANTipoRelatorioFunc = new javax.swing.JPanel();
        RBTSimples = new javax.swing.JRadioButton();
        RBTAvancado = new javax.swing.JRadioButton();
        RBTOtrosFunc = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        rolagem1 = new javax.swing.JScrollPane();
        folhaFuncionarios = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rolagem2 = new javax.swing.JScrollPane();
        folhaClientes = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        rolagemFornecedor = new javax.swing.JScrollPane();
        folhaFornecedores = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        rolagem4 = new javax.swing.JScrollPane();
        folhaVeiculos = new javax.swing.JLabel();

        CBXTipoImpresao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Funcionarios", "Clientes", "Fornecedor", "Veiculos" }));

        BOTImprimir.setText("Imprimir");
        BOTImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tipoFuncLayout = new javax.swing.GroupLayout(tipoFunc);
        tipoFunc.setLayout(tipoFuncLayout);
        tipoFuncLayout.setHorizontalGroup(
            tipoFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
        );
        tipoFuncLayout.setVerticalGroup(
            tipoFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );

        tabelaDados.addTab("Funcionario", tipoFunc);

        javax.swing.GroupLayout tipoCliLayout = new javax.swing.GroupLayout(tipoCli);
        tipoCli.setLayout(tipoCliLayout);
        tipoCliLayout.setHorizontalGroup(
            tipoCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
        );
        tipoCliLayout.setVerticalGroup(
            tipoCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );

        tabelaDados.addTab("Cliente", tipoCli);

        javax.swing.GroupLayout tipoFornLayout = new javax.swing.GroupLayout(tipoForn);
        tipoForn.setLayout(tipoFornLayout);
        tipoFornLayout.setHorizontalGroup(
            tipoFornLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
            .addGap(0, 702, Short.MAX_VALUE)
        );
        tipoFornLayout.setVerticalGroup(
            tipoFornLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
            .addGap(0, 384, Short.MAX_VALUE)
        );

        tabelaDados.addTab("Fornecedor", tipoForn);

        javax.swing.GroupLayout tipoVeiLayout = new javax.swing.GroupLayout(tipoVei);
        tipoVei.setLayout(tipoVeiLayout);
        tipoVeiLayout.setHorizontalGroup(
            tipoVeiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
            .addGap(0, 702, Short.MAX_VALUE)
            .addGap(0, 702, Short.MAX_VALUE)
        );
        tipoVeiLayout.setVerticalGroup(
            tipoVeiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
            .addGap(0, 384, Short.MAX_VALUE)
            .addGap(0, 384, Short.MAX_VALUE)
        );

        tabelaDados.addTab("Veiculo", tipoVei);

        PANTipoRelatorioFunc.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Relatorio"));

        GRBTipoRelatorio.add(RBTSimples);
        RBTSimples.setText("Simples");
        RBTSimples.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                RBTSimplesItemStateChanged(evt);
            }
        });

        GRBTipoRelatorio.add(RBTAvancado);
        RBTAvancado.setText("Avançado");
        RBTAvancado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                RBTAvancadoItemStateChanged(evt);
            }
        });

        GRBTipoRelatorio.add(RBTOtrosFunc);
        RBTOtrosFunc.setText("Outro");
        RBTOtrosFunc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                RBTOtrosFuncItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout PANTipoRelatorioFuncLayout = new javax.swing.GroupLayout(PANTipoRelatorioFunc);
        PANTipoRelatorioFunc.setLayout(PANTipoRelatorioFuncLayout);
        PANTipoRelatorioFuncLayout.setHorizontalGroup(
            PANTipoRelatorioFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANTipoRelatorioFuncLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RBTSimples)
                .addGap(18, 18, 18)
                .addComponent(RBTAvancado)
                .addGap(18, 18, 18)
                .addComponent(RBTOtrosFunc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PANTipoRelatorioFuncLayout.setVerticalGroup(
            PANTipoRelatorioFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANTipoRelatorioFuncLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PANTipoRelatorioFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBTSimples)
                    .addComponent(RBTAvancado)
                    .addComponent(RBTOtrosFunc)))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(673, Short.MAX_VALUE)
                .addComponent(BOTImprimir)
                .addGap(185, 185, 185))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(CBXTipoImpresao, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(PANTipoRelatorioFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(470, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(tabelaDados, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(CBXTipoImpresao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(PANTipoRelatorioFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(tabelaDados, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(BOTImprimir)
                .addContainerGap())
        );

        PainelImpressao.addTab("Main", jPanel5);

        rolagem1.setViewportView(folhaFuncionarios);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rolagem1, javax.swing.GroupLayout.DEFAULT_SIZE, 929, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rolagem1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
        );

        PainelImpressao.addTab("Funcionarios", jPanel1);

        jPanel2.setFocusTraversalPolicyProvider(true);

        rolagem2.setViewportView(folhaClientes);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rolagem2, javax.swing.GroupLayout.DEFAULT_SIZE, 929, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rolagem2, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
        );

        PainelImpressao.addTab("Clientes", jPanel2);

        rolagemFornecedor.setViewportView(folhaFornecedores);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rolagemFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 929, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rolagemFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
        );

        PainelImpressao.addTab("Fornecedor", jPanel3);

        rolagem4.setViewportView(folhaVeiculos);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rolagem4, javax.swing.GroupLayout.DEFAULT_SIZE, 929, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rolagem4, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
        );

        PainelImpressao.addTab("Veiculos", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelImpressao, javax.swing.GroupLayout.DEFAULT_SIZE, 934, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelImpressao, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

private void BOTImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTImprimirActionPerformed

    int linha = 0;
    PrinterMatrix printer = new PrinterMatrix();
    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");



    switch (CBXTipoImpresao.getSelectedIndex()) {
        case 0:
            JOptionPane.showMessageDialog(null, "Selecione um tipo de Dado para impressão");
            break;

        case 1:
            PainelImpressao.setSelectedIndex(1);

            queryFuncionarios = entityManager.createNamedQuery("Funcionario.findAll");
            List<sys.taxi.com.br.bean.Funcionario> funcionarios = queryFuncionarios.getResultList();

            printer.setOutSize(funcionarios.size() +9, 70);
                printer.printCharAtLin(1, funcionarios.size() +9, 1, "*");
                printer.printCharAtLin(1, funcionarios.size() +9, 70, "*");
                printer.printCharAtCol(1, 2, 69, "*");
                printer.printTextLinCol(2, 1, "==============Sistema VGCT - Relatorio de Lucro de caixa=============");//42
                printer.printCharAtCol(3, 2, 69, "*");

            
            if (RBTSimples.isSelected()) {
            printer.printTextLinCol(4, 2, "Nome Funcionario");
            printer.printTextLinCol(4, 20, "| CPF");
            printer.printTextLinCol(4, 31, "| Data Nascimento");
            printer.printTextLinCol(4, 42, "| Telefone");
            printer.printTextLinCol(4, 53, "| Data Admição");
            printer.printCharAtCol(5, 2, 69, "-");

                
                
                linha = 6;
                for (sys.taxi.com.br.bean.Funcionario func : funcionarios) {
                    printer.printTextLinCol(linha, 2, func.getNomefunc());
                    printer.printTextLinCol(linha, 20, "| " + func.getCpffunc());
                    
                    if (func.getDatanasfunc() == null){
                        printer.printTextLinCol(linha, 31, "| " + "Sem Data");
                    
                    }else{
                        printer.printTextLinCol(linha, 31, "| " + formato.format(func.getDatanasfunc()));
                    }
                    
                    printer.printTextLinCol(linha, 42, func.getTelefonefunc());
                    
                    if (func.getDataadmicaofunc() != null){
                    printer.printTextLinCol(linha, 53, "| " + formato.format(func.getDataadmicaofunc()));
                    }else{
                        printer.printTextLinCol(linha, 53, "| " + "Sem Data");
                    }
                    
                    //printer.printCharAtCol(linha + 1, 2, 60, "-");

                    linha++;

                }

            } else {
                if (RBTAvancado.isSelected()) {
            printer.printTextLinCol(4, 2, "Nome Func");
            printer.printTextLinCol(4, 16, "| CPF");
            printer.printTextLinCol(4, 27, "| Data Nasci");
            printer.printTextLinCol(4, 38, "| Telefone");
            printer.printTextLinCol(4, 49, "| Data Admição");
            printer.printTextLinCol(4, 60, "| CEP");
            printer.printCharAtCol(5, 2, 69, "-");   
                    
                    
                         linha = 6;
                for (sys.taxi.com.br.bean.Funcionario func : funcionarios) {
                    printer.printTextLinCol(linha, 2, func.getNomefunc());
                    printer.printTextLinCol(linha, 16, "| " + func.getCpffunc());
                    if (func.getDatanasfunc() == null){
                        printer.printTextLinCol(linha, 27, "| " + "Sem Data");
                    
                    }else{
                        printer.printTextLinCol(linha, 27, "| " + formato.format(func.getDatanasfunc()));
                    }
                    
                    printer.printTextLinCol(linha, 38,  "| " + func.getTelefonefunc());
                    if (func.getDataadmicaofunc() != null){
                    printer.printTextLinCol(linha, 49, "| " + formato.format(func.getDataadmicaofunc()));
                    }else{
                        printer.printTextLinCol(linha, 56, "| " + "Sem Data");
                    }
                    printer.printTextLinCol(linha, 60, "| " + func.getCepfunc());
                    
                    //printer.printCharAtCol(linha + 1, 2, 60, "-");

                    linha++;

                }

                }
            }
//printer.printTextLinCol( 2, 1, printer.centralizar(70, "Sistema VGCT - Relatorio de Lucro de caixa"));//42
//printer.printTextLinCol( 3, 1, printer.centralizar(70, "Sistema VGCT - Relatorio de Lucro de caixa"));//42
            printer.printCharAtCol(linha, 2, 69, "=");
            printer.printCharAtCol(linha + 1, 2, 70, "*");



            printer.toImageFile("src/sys/taxi/com/all/Images/Imprensao/funcionarios.jpg");
            /*    
            
             ***************************************************************** 
             *========== Sistema VGCT - Relatorio de Funcionarios ===========*
             * 
             * 
             * 
             * 
             * 
             * 
             * 
             * 
             * 
             **************************************************************** 
            
             */

            //areaRelatorio.setText(carregaArquivo("veiculos.txt"));
            //areaRelatorio.moveCaretPosition(0);
            //jLabel1.setIcon(new ImageIcon("src/veiculos.jpg"));
            folhaFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/Imprensao/funcionarios.jpg")));


            break;
        case 2:
            PainelImpressao.setSelectedIndex(2);



            queryClientes = entityManager.createNamedQuery("Cliente.findAll");
            List<sys.taxi.com.br.bean.Cliente> clientes = queryClientes.getResultList();



            printer.setOutSize(clientes.size() + 6, 70);
            printer.printCharAtCol(1, 1, 70, "=");
            printer.printTextLinCol(2, 1, printer.centralizar(70, "Sistema VGCT - Relatorio de Lucro de caixa"));//42

            printer.printCharAtCol(3, 1, 70, "*");
            printer.printTextLinCol(4, 1, "Nome Cliente");
            printer.printTextLinCol(4, 30, "| Celular");
            printer.printTextLinCol(4, 48, "| Data Cadastro");
            printer.printCharAtCol(5, 1, 70, "-");

            linha = 6;
            for (sys.taxi.com.br.bean.Cliente cli : clientes) {
                printer.printTextLinCol(linha, 1, cli.getNomecli());
                printer.printTextLinCol(linha, 30, "| " + cli.getCelularcli());
                printer.printTextLinCol(linha, 48, "| " + cli.getDatacadastrocli());
                printer.printCharAtCol(linha + 1, 1, 60, "-");

                linha++;

            }


            printer.printCharAtCol(linha, 1, 70, "=");
            printer.toImageFile("src/sys/taxi/com/all/Images/Imprensao/clientes.jpg");


            //areaRelatorio.setText(carregaArquivo("veiculos.txt"));
            //areaRelatorio.moveCaretPosition(0);
            //jLabel1.setIcon(new ImageIcon("src/veiculos.jpg"));
            folhaClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/Imprensao/clientes.jpg")));




            break;
        case 3:


            queryFornecedores = entityManager.createNamedQuery("Fornecedor.findAll");
            List<sys.taxi.com.br.bean.Fornecedor> fornecedores = queryFornecedores.getResultList();



            printer.setOutSize(fornecedores.size() + 6, 70);
            printer.printCharAtCol(1, 1, 70, "=");
            printer.printTextLinCol(2, 1, printer.centralizar(70, "Sistema VGCT - Relatorio de Lucro de caixa"));//42

            printer.printCharAtCol(3, 1, 70, "*");
            printer.printTextLinCol(4, 1, "Nome Fornecedor");
            printer.printTextLinCol(4, 30, "| CPF");
            printer.printTextLinCol(4, 50, "| Organização");
            printer.printCharAtCol(5, 1, 70, "-");

            linha = 6;
            for (sys.taxi.com.br.bean.Fornecedor forn : fornecedores) {
                printer.printTextLinCol(linha, 1, forn.getNomeforn());
                printer.printTextLinCol(linha, 30, "| " + forn.getCpfforn());
                printer.printTextLinCol(linha, 50, "| " + forn.getOrganizacaoforn());
                printer.printCharAtCol(linha + 1, 1, 60, "-");

                linha++;

            }


            printer.printCharAtCol(linha, 1, 70, "=");
            printer.toImageFile("src/sys/taxi/com/all/Images/Imprensao/fornecedores.jpg");


            //areaRelatorio.setText(carregaArquivo("veiculos.txt"));
            //areaRelatorio.moveCaretPosition(0);
            //jLabel1.setIcon(new ImageIcon("src/veiculos.jpg"));
            folhaFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/Imprensao/fornecedores.jpg")));

            PainelImpressao.setSelectedIndex(3);

            break;
        case 4:

            PrinterMatrix print = new PrinterMatrix();
            queryVeiculos = entityManager.createNamedQuery("Veiculo.findAll");
            List<sys.taxi.com.br.bean.Veiculo> veiculos = queryVeiculos.getResultList();



            print.setOutSize(veiculos.size() + 6, 70);
            print.printCharAtCol(1, 1, 70, "=");
            print.printTextLinCol(2, 1, print.centralizar(70, "Sistema VGCT - Relatorio de Lucro de caixa"));//42

            print.printCharAtCol(3, 1, 70, "*");
            print.printTextLinCol(4, 1, "Nome Veiculos");
            print.printTextLinCol(4, 30, "| Nome Fornecedor");
            print.printTextLinCol(4, 60, "| Placa");
            print.printCharAtCol(5, 1, 70, "-");

            linha = 6;
            for (sys.taxi.com.br.bean.Veiculo v : veiculos) {
                print.printTextLinCol(linha, 1, v.getNomevei());
                print.printTextLinCol(linha, 30, "| " + v.getCodforn().getNomeforn());
                print.printTextLinCol(linha, 60, "| " + v.getPlacavei());
                print.printCharAtCol(linha + 1, 1, 60, "-");

                linha++;

            }


            print.printCharAtCol(linha, 1, 70, "=");
            print.toImageFile("src/sys/taxi/com/all/Images/Imprensao/veiculos.jpg");


            //areaRelatorio.setText(carregaArquivo("veiculos.txt"));
            //areaRelatorio.moveCaretPosition(0);
            //jLabel1.setIcon(new ImageIcon("src/veiculos.jpg"));
            folhaVeiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sys/taxi/com/all/Images/Imprensao/veiculos.jpg")));

            PainelImpressao.setSelectedIndex(4);


            break;
    }

}//GEN-LAST:event_BOTImprimirActionPerformed

private void RBTSimplesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_RBTSimplesItemStateChanged
    tabelaDados.setVisible(false);
}//GEN-LAST:event_RBTSimplesItemStateChanged

private void RBTAvancadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_RBTAvancadoItemStateChanged
    tabelaDados.setVisible(false);
}//GEN-LAST:event_RBTAvancadoItemStateChanged

private void RBTOtrosFuncItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_RBTOtrosFuncItemStateChanged
    tabelaDados.setVisible(true);
}//GEN-LAST:event_RBTOtrosFuncItemStateChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTImprimir;
    private javax.swing.JComboBox CBXTipoImpresao;
    private javax.swing.ButtonGroup GRBTipoRelatorio;
    private javax.swing.JPanel PANTipoRelatorioFunc;
    private javax.swing.JTabbedPane PainelImpressao;
    private javax.swing.JRadioButton RBTAvancado;
    private javax.swing.JRadioButton RBTOtrosFunc;
    private javax.swing.JRadioButton RBTSimples;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel folhaClientes;
    private javax.swing.JLabel folhaFornecedores;
    private javax.swing.JLabel folhaFuncionarios;
    private javax.swing.JLabel folhaVeiculos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.persistence.Query queryClientes;
    private javax.persistence.Query queryFornecedores;
    private javax.persistence.Query queryFuncionarios;
    private javax.persistence.Query queryVeiculos;
    private javax.swing.JScrollPane rolagem1;
    private javax.swing.JScrollPane rolagem2;
    private javax.swing.JScrollPane rolagem4;
    private javax.swing.JScrollPane rolagemFornecedor;
    private javax.swing.JTabbedPane tabelaDados;
    private javax.swing.JPanel tipoCli;
    private javax.swing.JPanel tipoForn;
    private javax.swing.JPanel tipoFunc;
    private javax.swing.JPanel tipoVei;
    // End of variables declaration//GEN-END:variables

    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {

            public void run() {
                JFrame frame = new JFrame();
                frame.setContentPane(new ViewRelatorios());
                frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                frame.pack();
                frame.setVisible(true);
            }
        });
    }
}
